import type { MigrationContext } from '../migration.types';

export async function up({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
CREATE TABLE statistics.indicator (
  indicator_id uuid NOT NULL PRIMARY KEY,
  statistical_domain_id uuid NOT NULL,
  owner_organization_id uuid NOT NULL,
  code varchar(80) NOT NULL,
  name varchar(250) NOT NULL,
  short_name varchar(120),
  definition text NOT NULL,
  indicator_type varchar(40) NOT NULL,
  data_nature varchar(40) NOT NULL,
  preferred_direction varchar(20),
  is_active boolean NOT NULL,
  CONSTRAINT uq_indicator_owner_organization_id_code UNIQUE (owner_organization_id, code),
  CONSTRAINT ck_indicator_data_nature CHECK (data_nature IN ('OFFICIAL_STATISTIC','ADMINISTRATIVE_RECORD','OFFICIAL_EXTERNAL','OBSERVATORY_DERIVED','ACADEMIC_ESTIMATE','EXPERIMENTAL','FORECAST','SCENARIO'))
);

CREATE TABLE statistics.indicator_version (
  indicator_version_id uuid NOT NULL PRIMARY KEY,
  indicator_id uuid NOT NULL,
  methodology_version_id uuid,
  unit_measure_id uuid NOT NULL,
  frequency_id uuid NOT NULL,
  version_number integer NOT NULL,
  definition text NOT NULL,
  calculation_formula text,
  valid_from date NOT NULL,
  valid_to date,
  change_reason text,
  CONSTRAINT uq_indicator_version_indicator_id_version_number UNIQUE (indicator_id, version_number),
  CONSTRAINT ck_indicator_version_valid_from_valid_to CHECK (valid_to IS NULL OR valid_to >= valid_from),
  CONSTRAINT ck_indicator_version_number CHECK (version_number > 0)
);

CREATE TABLE statistics.dataset_indicator (
  dataset_indicator_id uuid NOT NULL PRIMARY KEY,
  dataset_version_id uuid NOT NULL,
  indicator_version_id uuid NOT NULL,
  is_primary boolean NOT NULL,
  sort_order integer NOT NULL,
  CONSTRAINT uq_dataset_indicator_dataset_version_id_indicator_version_id UNIQUE (dataset_version_id, indicator_version_id)
);

CREATE TABLE statistics.series (
  series_id uuid NOT NULL PRIMARY KEY,
  dataset_version_id uuid NOT NULL,
  indicator_version_id uuid,
  frequency_id uuid NOT NULL,
  unit_measure_id uuid,
  series_key text NOT NULL,
  series_key_hash char(64) NOT NULL,
  status varchar(30) NOT NULL,
  valid_from date,
  valid_to date,
  CONSTRAINT uq_series_dataset_version_id_series_key_hash UNIQUE (dataset_version_id, series_key_hash),
  CONSTRAINT ck_series_valid_from_valid_to CHECK (valid_to IS NULL OR valid_to >= valid_from),
  CONSTRAINT ck_series_status CHECK (status IN ('ACTIVE','SUSPENDED','DISCONTINUED','SUPERSEDED'))
);

CREATE TABLE statistics.series_dimension_value (
  series_dimension_value_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  series_id uuid NOT NULL,
  dimension_definition_id uuid NOT NULL,
  code_item_id uuid,
  classification_item_id uuid,
  geographic_unit_id uuid,
  text_value text,
  numeric_value numeric(38,12),
  date_value date,
  CONSTRAINT uq_series_dimension_value_series_id_dimension_definition_id UNIQUE (series_id, dimension_definition_id),
  CONSTRAINT ck_series_dimension_one_value CHECK (num_nonnulls(code_item_id, classification_item_id, geographic_unit_id, text_value, numeric_value, date_value) = 1)
);

CREATE TABLE statistics.observation (
  observation_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  series_id uuid NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  period_code varchar(40) NOT NULL,
  reference_date date,
  CONSTRAINT uq_observation_series_id_period_start_period_end UNIQUE (series_id, period_start, period_end),
  CONSTRAINT ck_observation_period CHECK (period_end >= period_start)
);

CREATE TABLE statistics.observation_revision (
  observation_revision_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  observation_id bigint NOT NULL,
  source_artifact_id uuid NOT NULL,
  data_entry_batch_id uuid NOT NULL,
  revision_number integer NOT NULL,
  status varchar(30) NOT NULL,
  confidentiality_status varchar(30) NOT NULL,
  publication_date date,
  capture_date timestamptz NOT NULL,
  vintage_date date NOT NULL,
  valid_from timestamptz NOT NULL,
  valid_to timestamptz,
  is_current boolean NOT NULL,
  revision_reason text,
  normalized_hash char(64) NOT NULL,
  CONSTRAINT uq_observation_revision_observation_id_revision_number UNIQUE (observation_id, revision_number),
  CONSTRAINT ck_observation_revision_valid_from_valid_to CHECK (valid_to IS NULL OR valid_to >= valid_from),
  CONSTRAINT ck_observation_revision_status CHECK (status IN ('DRAFT','VALIDATED','PUBLISHED','SUPERSEDED','WITHDRAWN','REJECTED')),
  CONSTRAINT ck_observation_revision_number CHECK (revision_number > 0),
  CONSTRAINT ck_observation_revision_validity CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE TABLE statistics.observation_measure (
  observation_measure_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  observation_revision_id bigint NOT NULL,
  measure_definition_id uuid NOT NULL,
  numeric_value numeric(38,12),
  text_value text,
  boolean_value boolean,
  CONSTRAINT uq_observation_measure_observation_revision_id_measure_definit UNIQUE (observation_revision_id, measure_definition_id),
  CONSTRAINT ck_observation_measure_one_value CHECK (num_nonnulls(numeric_value, text_value, boolean_value) = 1)
);

CREATE TABLE statistics.observation_attribute_value (
  observation_attribute_value_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  observation_revision_id bigint NOT NULL,
  attribute_definition_id uuid NOT NULL,
  code_item_id uuid,
  numeric_value numeric(38,12),
  text_value text,
  boolean_value boolean,
  CONSTRAINT uq_observation_attribute_value_observation_revision_id_attribu UNIQUE (observation_revision_id, attribute_definition_id),
  CONSTRAINT ck_observation_attribute_one_value CHECK (num_nonnulls(code_item_id, numeric_value, text_value, boolean_value) = 1)
);
  `);
}

export async function down({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
DROP TABLE IF EXISTS statistics.observation_attribute_value CASCADE;
DROP TABLE IF EXISTS statistics.observation_measure CASCADE;
DROP TABLE IF EXISTS statistics.observation_revision CASCADE;
DROP TABLE IF EXISTS statistics.observation CASCADE;
DROP TABLE IF EXISTS statistics.series_dimension_value CASCADE;
DROP TABLE IF EXISTS statistics.series CASCADE;
DROP TABLE IF EXISTS statistics.dataset_indicator CASCADE;
DROP TABLE IF EXISTS statistics.indicator_version CASCADE;
DROP TABLE IF EXISTS statistics.indicator CASCADE;
  `);
}
