import type { MigrationContext } from '../migration.types';

export async function up({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
CREATE TABLE quality_lineage.quality_dimension (
  quality_dimension_id uuid NOT NULL PRIMARY KEY,
  code varchar(50) NOT NULL UNIQUE,
  name varchar(180) NOT NULL,
  description text
);

CREATE TABLE quality_lineage.quality_rule (
  quality_rule_id uuid NOT NULL PRIMARY KEY,
  quality_dimension_id uuid NOT NULL,
  code varchar(80) NOT NULL UNIQUE,
  name varchar(250) NOT NULL,
  rule_type varchar(40) NOT NULL,
  severity varchar(20) NOT NULL,
  target_entity_type varchar(40) NOT NULL,
  configuration_json jsonb NOT NULL,
  is_active boolean NOT NULL
);

CREATE TABLE quality_lineage.quality_assessment (
  quality_assessment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  quality_rule_id uuid NOT NULL,
  data_entry_batch_id uuid,
  target_entity_type varchar(40) NOT NULL,
  target_entity_id varchar(80) NOT NULL,
  status varchar(20) NOT NULL,
  measured_value text,
  threshold_value text,
  details jsonb NOT NULL,
  assessed_at timestamptz NOT NULL
);

CREATE TABLE quality_lineage.data_issue (
  data_issue_id uuid NOT NULL PRIMARY KEY,
  quality_assessment_id bigint,
  issue_type varchar(40) NOT NULL,
  severity varchar(20) NOT NULL,
  target_entity_type varchar(40) NOT NULL,
  target_entity_id varchar(80) NOT NULL,
  title varchar(250) NOT NULL,
  description text NOT NULL,
  status varchar(30) NOT NULL,
  detected_at timestamptz NOT NULL,
  resolved_at timestamptz,
  resolution_notes text,
  CONSTRAINT ck_data_issue_status CHECK (status IN ('OPEN','TRIAGED','IN_CORRECTION','RESOLVED','VERIFIED','CLOSED','REOPENED','DISMISSED'))
);

CREATE TABLE quality_lineage.lineage_relation (
  lineage_relation_id uuid NOT NULL PRIMARY KEY,
  methodology_version_id uuid,
  source_entity_type varchar(40) NOT NULL,
  source_entity_id varchar(80) NOT NULL,
  target_entity_type varchar(40) NOT NULL,
  target_entity_id varchar(80) NOT NULL,
  relation_type varchar(40) NOT NULL,
  transformation_description text,
  formula text,
  created_at timestamptz NOT NULL
);

CREATE TABLE quality_lineage.indicator_relation (
  indicator_relation_id uuid NOT NULL PRIMARY KEY,
  source_indicator_version_id uuid NOT NULL,
  target_indicator_version_id uuid NOT NULL,
  relation_type varchar(40) NOT NULL,
  formula text,
  description text,
  valid_from date,
  valid_to date,
  CONSTRAINT ck_indicator_relation_valid_from_valid_to CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE TABLE quality_lineage.series_break (
  series_break_id uuid NOT NULL PRIMARY KEY,
  series_id uuid NOT NULL,
  methodology_version_id uuid,
  break_date date NOT NULL,
  break_type varchar(40) NOT NULL,
  reason text NOT NULL,
  is_comparable_before_after boolean NOT NULL,
  linking_method text,
  notes text
);
  `);
}

export async function down({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
DROP TABLE IF EXISTS quality_lineage.series_break CASCADE;
DROP TABLE IF EXISTS quality_lineage.indicator_relation CASCADE;
DROP TABLE IF EXISTS quality_lineage.lineage_relation CASCADE;
DROP TABLE IF EXISTS quality_lineage.data_issue CASCADE;
DROP TABLE IF EXISTS quality_lineage.quality_assessment CASCADE;
DROP TABLE IF EXISTS quality_lineage.quality_rule CASCADE;
DROP TABLE IF EXISTS quality_lineage.quality_dimension CASCADE;
  `);
}
