import type { MigrationContext } from '../migration.types';

export async function up({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
ALTER TABLE provenance.organization ADD CONSTRAINT fk_organization_parent_organization_id FOREIGN KEY (parent_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE provenance.source ADD CONSTRAINT fk_source_organization_id FOREIGN KEY (organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE provenance.source ADD CONSTRAINT fk_source_frequency_id FOREIGN KEY (frequency_id) REFERENCES semantic.frequency (frequency_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE provenance.source_artifact ADD CONSTRAINT fk_source_artifact_source_id FOREIGN KEY (source_id) REFERENCES provenance.source (source_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE provenance.data_entry_batch ADD CONSTRAINT fk_data_entry_batch_dataset_version_id FOREIGN KEY (dataset_version_id) REFERENCES metadata.dataset_version (dataset_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE provenance.data_entry_batch ADD CONSTRAINT fk_data_entry_batch_source_artifact_id FOREIGN KEY (source_artifact_id) REFERENCES provenance.source_artifact (source_artifact_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE provenance.data_entry_batch ADD CONSTRAINT fk_data_entry_batch_submitted_by_organization_id FOREIGN KEY (submitted_by_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.statistical_domain ADD CONSTRAINT fk_statistical_domain_parent_domain_id FOREIGN KEY (parent_domain_id) REFERENCES semantic.statistical_domain (statistical_domain_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.concept ADD CONSTRAINT fk_concept_owner_organization_id FOREIGN KEY (owner_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.code_list ADD CONSTRAINT fk_code_list_owner_organization_id FOREIGN KEY (owner_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.code_item ADD CONSTRAINT fk_code_item_code_list_id FOREIGN KEY (code_list_id) REFERENCES semantic.code_list (code_list_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.code_item ADD CONSTRAINT fk_code_item_parent_code_item_id FOREIGN KEY (parent_code_item_id) REFERENCES semantic.code_item (code_item_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.classification ADD CONSTRAINT fk_classification_custodian_organization_id FOREIGN KEY (custodian_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.classification_version ADD CONSTRAINT fk_classification_version_classification_id FOREIGN KEY (classification_id) REFERENCES semantic.classification (classification_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.classification_item ADD CONSTRAINT fk_classification_item_classification_version_id FOREIGN KEY (classification_version_id) REFERENCES semantic.classification_version (classification_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.classification_item ADD CONSTRAINT fk_classification_item_parent_item_id FOREIGN KEY (parent_item_id) REFERENCES semantic.classification_item (classification_item_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.classification_mapping ADD CONSTRAINT fk_classification_mapping_source_item_id FOREIGN KEY (source_item_id) REFERENCES semantic.classification_item (classification_item_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.classification_mapping ADD CONSTRAINT fk_classification_mapping_target_item_id FOREIGN KEY (target_item_id) REFERENCES semantic.classification_item (classification_item_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.geographic_unit ADD CONSTRAINT fk_geographic_unit_parent_geographic_unit_id FOREIGN KEY (parent_geographic_unit_id) REFERENCES semantic.geographic_unit (geographic_unit_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE semantic.unit_measure ADD CONSTRAINT fk_unit_measure_base_unit_measure_id FOREIGN KEY (base_unit_measure_id) REFERENCES semantic.unit_measure (unit_measure_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.statistical_operation ADD CONSTRAINT fk_statistical_operation_producer_organization_id FOREIGN KEY (producer_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.methodology ADD CONSTRAINT fk_methodology_owner_organization_id FOREIGN KEY (owner_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.methodology_version ADD CONSTRAINT fk_methodology_version_methodology_id FOREIGN KEY (methodology_id) REFERENCES metadata.methodology (methodology_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dataset ADD CONSTRAINT fk_dataset_statistical_operation_id FOREIGN KEY (statistical_operation_id) REFERENCES metadata.statistical_operation (statistical_operation_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dataset ADD CONSTRAINT fk_dataset_source_id FOREIGN KEY (source_id) REFERENCES provenance.source (source_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dataset ADD CONSTRAINT fk_dataset_producer_organization_id FOREIGN KEY (producer_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dataset ADD CONSTRAINT fk_dataset_statistical_domain_id FOREIGN KEY (statistical_domain_id) REFERENCES semantic.statistical_domain (statistical_domain_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dataset_version ADD CONSTRAINT fk_dataset_version_dataset_id FOREIGN KEY (dataset_id) REFERENCES metadata.dataset (dataset_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dataset_version ADD CONSTRAINT fk_dataset_version_methodology_version_id FOREIGN KEY (methodology_version_id) REFERENCES metadata.methodology_version (methodology_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dataset_version ADD CONSTRAINT fk_dataset_version_data_structure_id FOREIGN KEY (data_structure_id) REFERENCES metadata.data_structure (data_structure_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.data_structure ADD CONSTRAINT fk_data_structure_owner_organization_id FOREIGN KEY (owner_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dimension_definition ADD CONSTRAINT fk_dimension_definition_data_structure_id FOREIGN KEY (data_structure_id) REFERENCES metadata.data_structure (data_structure_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dimension_definition ADD CONSTRAINT fk_dimension_definition_concept_id FOREIGN KEY (concept_id) REFERENCES semantic.concept (concept_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dimension_definition ADD CONSTRAINT fk_dimension_definition_code_list_id FOREIGN KEY (code_list_id) REFERENCES semantic.code_list (code_list_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.dimension_definition ADD CONSTRAINT fk_dimension_definition_classification_version_id FOREIGN KEY (classification_version_id) REFERENCES semantic.classification_version (classification_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.measure_definition ADD CONSTRAINT fk_measure_definition_data_structure_id FOREIGN KEY (data_structure_id) REFERENCES metadata.data_structure (data_structure_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.measure_definition ADD CONSTRAINT fk_measure_definition_concept_id FOREIGN KEY (concept_id) REFERENCES semantic.concept (concept_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.measure_definition ADD CONSTRAINT fk_measure_definition_unit_measure_id FOREIGN KEY (unit_measure_id) REFERENCES semantic.unit_measure (unit_measure_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.attribute_definition ADD CONSTRAINT fk_attribute_definition_data_structure_id FOREIGN KEY (data_structure_id) REFERENCES metadata.data_structure (data_structure_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.attribute_definition ADD CONSTRAINT fk_attribute_definition_concept_id FOREIGN KEY (concept_id) REFERENCES semantic.concept (concept_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE metadata.attribute_definition ADD CONSTRAINT fk_attribute_definition_code_list_id FOREIGN KEY (code_list_id) REFERENCES semantic.code_list (code_list_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.indicator ADD CONSTRAINT fk_indicator_statistical_domain_id FOREIGN KEY (statistical_domain_id) REFERENCES semantic.statistical_domain (statistical_domain_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.indicator ADD CONSTRAINT fk_indicator_owner_organization_id FOREIGN KEY (owner_organization_id) REFERENCES provenance.organization (organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.indicator_version ADD CONSTRAINT fk_indicator_version_indicator_id FOREIGN KEY (indicator_id) REFERENCES statistics.indicator (indicator_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.indicator_version ADD CONSTRAINT fk_indicator_version_methodology_version_id FOREIGN KEY (methodology_version_id) REFERENCES metadata.methodology_version (methodology_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.indicator_version ADD CONSTRAINT fk_indicator_version_unit_measure_id FOREIGN KEY (unit_measure_id) REFERENCES semantic.unit_measure (unit_measure_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.indicator_version ADD CONSTRAINT fk_indicator_version_frequency_id FOREIGN KEY (frequency_id) REFERENCES semantic.frequency (frequency_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.dataset_indicator ADD CONSTRAINT fk_dataset_indicator_dataset_version_id FOREIGN KEY (dataset_version_id) REFERENCES metadata.dataset_version (dataset_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.dataset_indicator ADD CONSTRAINT fk_dataset_indicator_indicator_version_id FOREIGN KEY (indicator_version_id) REFERENCES statistics.indicator_version (indicator_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series ADD CONSTRAINT fk_series_dataset_version_id FOREIGN KEY (dataset_version_id) REFERENCES metadata.dataset_version (dataset_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series ADD CONSTRAINT fk_series_indicator_version_id FOREIGN KEY (indicator_version_id) REFERENCES statistics.indicator_version (indicator_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series ADD CONSTRAINT fk_series_frequency_id FOREIGN KEY (frequency_id) REFERENCES semantic.frequency (frequency_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series ADD CONSTRAINT fk_series_unit_measure_id FOREIGN KEY (unit_measure_id) REFERENCES semantic.unit_measure (unit_measure_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series_dimension_value ADD CONSTRAINT fk_series_dimension_value_series_id FOREIGN KEY (series_id) REFERENCES statistics.series (series_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series_dimension_value ADD CONSTRAINT fk_series_dimension_value_dimension_definition_id FOREIGN KEY (dimension_definition_id) REFERENCES metadata.dimension_definition (dimension_definition_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series_dimension_value ADD CONSTRAINT fk_series_dimension_value_code_item_id FOREIGN KEY (code_item_id) REFERENCES semantic.code_item (code_item_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series_dimension_value ADD CONSTRAINT fk_series_dimension_value_classification_item_id FOREIGN KEY (classification_item_id) REFERENCES semantic.classification_item (classification_item_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.series_dimension_value ADD CONSTRAINT fk_series_dimension_value_geographic_unit_id FOREIGN KEY (geographic_unit_id) REFERENCES semantic.geographic_unit (geographic_unit_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation ADD CONSTRAINT fk_observation_series_id FOREIGN KEY (series_id) REFERENCES statistics.series (series_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation_revision ADD CONSTRAINT fk_observation_revision_observation_id FOREIGN KEY (observation_id) REFERENCES statistics.observation (observation_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation_revision ADD CONSTRAINT fk_observation_revision_source_artifact_id FOREIGN KEY (source_artifact_id) REFERENCES provenance.source_artifact (source_artifact_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation_revision ADD CONSTRAINT fk_observation_revision_data_entry_batch_id FOREIGN KEY (data_entry_batch_id) REFERENCES provenance.data_entry_batch (data_entry_batch_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation_measure ADD CONSTRAINT fk_observation_measure_observation_revision_id FOREIGN KEY (observation_revision_id) REFERENCES statistics.observation_revision (observation_revision_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation_measure ADD CONSTRAINT fk_observation_measure_measure_definition_id FOREIGN KEY (measure_definition_id) REFERENCES metadata.measure_definition (measure_definition_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation_attribute_value ADD CONSTRAINT fk_observation_attribute_value_observation_revision_id FOREIGN KEY (observation_revision_id) REFERENCES statistics.observation_revision (observation_revision_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation_attribute_value ADD CONSTRAINT fk_observation_attribute_value_attribute_definition_id FOREIGN KEY (attribute_definition_id) REFERENCES metadata.attribute_definition (attribute_definition_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE statistics.observation_attribute_value ADD CONSTRAINT fk_observation_attribute_value_code_item_id FOREIGN KEY (code_item_id) REFERENCES semantic.code_item (code_item_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.quality_rule ADD CONSTRAINT fk_quality_rule_quality_dimension_id FOREIGN KEY (quality_dimension_id) REFERENCES quality_lineage.quality_dimension (quality_dimension_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.quality_assessment ADD CONSTRAINT fk_quality_assessment_quality_rule_id FOREIGN KEY (quality_rule_id) REFERENCES quality_lineage.quality_rule (quality_rule_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.quality_assessment ADD CONSTRAINT fk_quality_assessment_data_entry_batch_id FOREIGN KEY (data_entry_batch_id) REFERENCES provenance.data_entry_batch (data_entry_batch_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.data_issue ADD CONSTRAINT fk_data_issue_quality_assessment_id FOREIGN KEY (quality_assessment_id) REFERENCES quality_lineage.quality_assessment (quality_assessment_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.lineage_relation ADD CONSTRAINT fk_lineage_relation_methodology_version_id FOREIGN KEY (methodology_version_id) REFERENCES metadata.methodology_version (methodology_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.indicator_relation ADD CONSTRAINT fk_indicator_relation_source_indicator_version_id FOREIGN KEY (source_indicator_version_id) REFERENCES statistics.indicator_version (indicator_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.indicator_relation ADD CONSTRAINT fk_indicator_relation_target_indicator_version_id FOREIGN KEY (target_indicator_version_id) REFERENCES statistics.indicator_version (indicator_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.series_break ADD CONSTRAINT fk_series_break_series_id FOREIGN KEY (series_id) REFERENCES statistics.series (series_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE quality_lineage.series_break ADD CONSTRAINT fk_series_break_methodology_version_id FOREIGN KEY (methodology_version_id) REFERENCES metadata.methodology_version (methodology_version_id) ON UPDATE CASCADE ON DELETE RESTRICT;
  `);
}

export async function down({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
ALTER TABLE quality_lineage.series_break DROP CONSTRAINT IF EXISTS fk_series_break_methodology_version_id;
ALTER TABLE quality_lineage.series_break DROP CONSTRAINT IF EXISTS fk_series_break_series_id;
ALTER TABLE quality_lineage.indicator_relation DROP CONSTRAINT IF EXISTS fk_indicator_relation_target_indicator_version_id;
ALTER TABLE quality_lineage.indicator_relation DROP CONSTRAINT IF EXISTS fk_indicator_relation_source_indicator_version_id;
ALTER TABLE quality_lineage.lineage_relation DROP CONSTRAINT IF EXISTS fk_lineage_relation_methodology_version_id;
ALTER TABLE quality_lineage.data_issue DROP CONSTRAINT IF EXISTS fk_data_issue_quality_assessment_id;
ALTER TABLE quality_lineage.quality_assessment DROP CONSTRAINT IF EXISTS fk_quality_assessment_data_entry_batch_id;
ALTER TABLE quality_lineage.quality_assessment DROP CONSTRAINT IF EXISTS fk_quality_assessment_quality_rule_id;
ALTER TABLE quality_lineage.quality_rule DROP CONSTRAINT IF EXISTS fk_quality_rule_quality_dimension_id;
ALTER TABLE statistics.observation_attribute_value DROP CONSTRAINT IF EXISTS fk_observation_attribute_value_code_item_id;
ALTER TABLE statistics.observation_attribute_value DROP CONSTRAINT IF EXISTS fk_observation_attribute_value_attribute_definition_id;
ALTER TABLE statistics.observation_attribute_value DROP CONSTRAINT IF EXISTS fk_observation_attribute_value_observation_revision_id;
ALTER TABLE statistics.observation_measure DROP CONSTRAINT IF EXISTS fk_observation_measure_measure_definition_id;
ALTER TABLE statistics.observation_measure DROP CONSTRAINT IF EXISTS fk_observation_measure_observation_revision_id;
ALTER TABLE statistics.observation_revision DROP CONSTRAINT IF EXISTS fk_observation_revision_data_entry_batch_id;
ALTER TABLE statistics.observation_revision DROP CONSTRAINT IF EXISTS fk_observation_revision_source_artifact_id;
ALTER TABLE statistics.observation_revision DROP CONSTRAINT IF EXISTS fk_observation_revision_observation_id;
ALTER TABLE statistics.observation DROP CONSTRAINT IF EXISTS fk_observation_series_id;
ALTER TABLE statistics.series_dimension_value DROP CONSTRAINT IF EXISTS fk_series_dimension_value_geographic_unit_id;
ALTER TABLE statistics.series_dimension_value DROP CONSTRAINT IF EXISTS fk_series_dimension_value_classification_item_id;
ALTER TABLE statistics.series_dimension_value DROP CONSTRAINT IF EXISTS fk_series_dimension_value_code_item_id;
ALTER TABLE statistics.series_dimension_value DROP CONSTRAINT IF EXISTS fk_series_dimension_value_dimension_definition_id;
ALTER TABLE statistics.series_dimension_value DROP CONSTRAINT IF EXISTS fk_series_dimension_value_series_id;
ALTER TABLE statistics.series DROP CONSTRAINT IF EXISTS fk_series_unit_measure_id;
ALTER TABLE statistics.series DROP CONSTRAINT IF EXISTS fk_series_frequency_id;
ALTER TABLE statistics.series DROP CONSTRAINT IF EXISTS fk_series_indicator_version_id;
ALTER TABLE statistics.series DROP CONSTRAINT IF EXISTS fk_series_dataset_version_id;
ALTER TABLE statistics.dataset_indicator DROP CONSTRAINT IF EXISTS fk_dataset_indicator_indicator_version_id;
ALTER TABLE statistics.dataset_indicator DROP CONSTRAINT IF EXISTS fk_dataset_indicator_dataset_version_id;
ALTER TABLE statistics.indicator_version DROP CONSTRAINT IF EXISTS fk_indicator_version_frequency_id;
ALTER TABLE statistics.indicator_version DROP CONSTRAINT IF EXISTS fk_indicator_version_unit_measure_id;
ALTER TABLE statistics.indicator_version DROP CONSTRAINT IF EXISTS fk_indicator_version_methodology_version_id;
ALTER TABLE statistics.indicator_version DROP CONSTRAINT IF EXISTS fk_indicator_version_indicator_id;
ALTER TABLE statistics.indicator DROP CONSTRAINT IF EXISTS fk_indicator_owner_organization_id;
ALTER TABLE statistics.indicator DROP CONSTRAINT IF EXISTS fk_indicator_statistical_domain_id;
ALTER TABLE metadata.attribute_definition DROP CONSTRAINT IF EXISTS fk_attribute_definition_code_list_id;
ALTER TABLE metadata.attribute_definition DROP CONSTRAINT IF EXISTS fk_attribute_definition_concept_id;
ALTER TABLE metadata.attribute_definition DROP CONSTRAINT IF EXISTS fk_attribute_definition_data_structure_id;
ALTER TABLE metadata.measure_definition DROP CONSTRAINT IF EXISTS fk_measure_definition_unit_measure_id;
ALTER TABLE metadata.measure_definition DROP CONSTRAINT IF EXISTS fk_measure_definition_concept_id;
ALTER TABLE metadata.measure_definition DROP CONSTRAINT IF EXISTS fk_measure_definition_data_structure_id;
ALTER TABLE metadata.dimension_definition DROP CONSTRAINT IF EXISTS fk_dimension_definition_classification_version_id;
ALTER TABLE metadata.dimension_definition DROP CONSTRAINT IF EXISTS fk_dimension_definition_code_list_id;
ALTER TABLE metadata.dimension_definition DROP CONSTRAINT IF EXISTS fk_dimension_definition_concept_id;
ALTER TABLE metadata.dimension_definition DROP CONSTRAINT IF EXISTS fk_dimension_definition_data_structure_id;
ALTER TABLE metadata.data_structure DROP CONSTRAINT IF EXISTS fk_data_structure_owner_organization_id;
ALTER TABLE metadata.dataset_version DROP CONSTRAINT IF EXISTS fk_dataset_version_data_structure_id;
ALTER TABLE metadata.dataset_version DROP CONSTRAINT IF EXISTS fk_dataset_version_methodology_version_id;
ALTER TABLE metadata.dataset_version DROP CONSTRAINT IF EXISTS fk_dataset_version_dataset_id;
ALTER TABLE metadata.dataset DROP CONSTRAINT IF EXISTS fk_dataset_statistical_domain_id;
ALTER TABLE metadata.dataset DROP CONSTRAINT IF EXISTS fk_dataset_producer_organization_id;
ALTER TABLE metadata.dataset DROP CONSTRAINT IF EXISTS fk_dataset_source_id;
ALTER TABLE metadata.dataset DROP CONSTRAINT IF EXISTS fk_dataset_statistical_operation_id;
ALTER TABLE metadata.methodology_version DROP CONSTRAINT IF EXISTS fk_methodology_version_methodology_id;
ALTER TABLE metadata.methodology DROP CONSTRAINT IF EXISTS fk_methodology_owner_organization_id;
ALTER TABLE metadata.statistical_operation DROP CONSTRAINT IF EXISTS fk_statistical_operation_producer_organization_id;
ALTER TABLE semantic.unit_measure DROP CONSTRAINT IF EXISTS fk_unit_measure_base_unit_measure_id;
ALTER TABLE semantic.geographic_unit DROP CONSTRAINT IF EXISTS fk_geographic_unit_parent_geographic_unit_id;
ALTER TABLE semantic.classification_mapping DROP CONSTRAINT IF EXISTS fk_classification_mapping_target_item_id;
ALTER TABLE semantic.classification_mapping DROP CONSTRAINT IF EXISTS fk_classification_mapping_source_item_id;
ALTER TABLE semantic.classification_item DROP CONSTRAINT IF EXISTS fk_classification_item_parent_item_id;
ALTER TABLE semantic.classification_item DROP CONSTRAINT IF EXISTS fk_classification_item_classification_version_id;
ALTER TABLE semantic.classification_version DROP CONSTRAINT IF EXISTS fk_classification_version_classification_id;
ALTER TABLE semantic.classification DROP CONSTRAINT IF EXISTS fk_classification_custodian_organization_id;
ALTER TABLE semantic.code_item DROP CONSTRAINT IF EXISTS fk_code_item_parent_code_item_id;
ALTER TABLE semantic.code_item DROP CONSTRAINT IF EXISTS fk_code_item_code_list_id;
ALTER TABLE semantic.code_list DROP CONSTRAINT IF EXISTS fk_code_list_owner_organization_id;
ALTER TABLE semantic.concept DROP CONSTRAINT IF EXISTS fk_concept_owner_organization_id;
ALTER TABLE semantic.statistical_domain DROP CONSTRAINT IF EXISTS fk_statistical_domain_parent_domain_id;
ALTER TABLE provenance.data_entry_batch DROP CONSTRAINT IF EXISTS fk_data_entry_batch_submitted_by_organization_id;
ALTER TABLE provenance.data_entry_batch DROP CONSTRAINT IF EXISTS fk_data_entry_batch_source_artifact_id;
ALTER TABLE provenance.data_entry_batch DROP CONSTRAINT IF EXISTS fk_data_entry_batch_dataset_version_id;
ALTER TABLE provenance.source_artifact DROP CONSTRAINT IF EXISTS fk_source_artifact_source_id;
ALTER TABLE provenance.source DROP CONSTRAINT IF EXISTS fk_source_frequency_id;
ALTER TABLE provenance.source DROP CONSTRAINT IF EXISTS fk_source_organization_id;
ALTER TABLE provenance.organization DROP CONSTRAINT IF EXISTS fk_organization_parent_organization_id;
  `);
}
