import type { MigrationContext } from '../migration.types';

/**
 * Registers autonomous collectors and preserves their raw submissions.
 *
 * `raw_observation` is the immutable landing zone required before any
 * normalization: the original payload must survive a defective transformation,
 * so runtime roles never receive UPDATE or DELETE on it.
 */
export async function up({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
CREATE TABLE intelligence.ai_agent (
  ai_agent_id uuid NOT NULL PRIMARY KEY,
  organization_id uuid NOT NULL,
  code varchar(80) NOT NULL UNIQUE,
  name varchar(250) NOT NULL,
  agent_type varchar(40) NOT NULL,
  provider varchar(80) NOT NULL,
  model_identifier varchar(120) NOT NULL,
  specialty varchar(120),
  prompt_version varchar(40) NOT NULL,
  schema_version varchar(40) NOT NULL,
  credential_fingerprint char(64),
  configuration_json jsonb NOT NULL,
  status varchar(30) NOT NULL,
  last_run_at timestamptz,
  is_active boolean NOT NULL,
  CONSTRAINT ck_ai_agent_status CHECK (status IN ('ACTIVE','SUSPENDED','RETIRED')),
  CONSTRAINT ck_ai_agent_type CHECK (agent_type IN ('EXCHANGE_RATE','SOVEREIGN_DEBT','SECTOR','SOCIOECONOMIC','SENTIMENT','UNCERTAINTY','CORPORATE','POLITICAL','SECURITIES_MARKET','FINANCIAL_SYSTEM','EXTERNAL_SECTOR')),
  CONSTRAINT ck_ai_agent_credential_fingerprint CHECK (credential_fingerprint IS NULL OR credential_fingerprint ~ '^[a-f0-9]{64}$')
);

CREATE TABLE intelligence.agent_run (
  agent_run_id uuid NOT NULL PRIMARY KEY,
  ai_agent_id uuid NOT NULL,
  correlation_id varchar(128) NOT NULL,
  trigger_type varchar(30) NOT NULL,
  attempt_no integer NOT NULL,
  status varchar(30) NOT NULL,
  started_at timestamptz NOT NULL,
  completed_at timestamptz,
  sources_consulted integer NOT NULL,
  records_received bigint NOT NULL,
  records_accepted bigint NOT NULL,
  records_rejected bigint NOT NULL,
  records_quarantined bigint NOT NULL,
  warning_count integer NOT NULL,
  error_summary text,
  checkpoint_json jsonb,
  estimated_cost_usd numeric(12,4),
  prompt_version varchar(40) NOT NULL,
  schema_version varchar(40) NOT NULL,
  CONSTRAINT ck_agent_run_status CHECK (status IN ('RUNNING','SUCCEEDED','PARTIAL','FAILED','CANCELLED')),
  CONSTRAINT ck_agent_run_trigger CHECK (trigger_type IN ('SCHEDULED','MANUAL','RETRY','BACKFILL')),
  CONSTRAINT ck_agent_run_attempt CHECK (attempt_no > 0),
  CONSTRAINT ck_agent_run_counts CHECK (records_received >= 0 AND records_accepted >= 0 AND records_rejected >= 0 AND records_quarantined >= 0),
  CONSTRAINT ck_agent_run_completion CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE intelligence.raw_observation (
  raw_observation_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  agent_run_id uuid NOT NULL,
  source_artifact_id uuid,
  payload_json jsonb NOT NULL,
  payload_hash char(64) NOT NULL,
  received_at timestamptz NOT NULL,
  processing_status varchar(30) NOT NULL,
  rejection_reason text,
  CONSTRAINT uq_raw_observation_agent_run_id_payload_hash UNIQUE (agent_run_id, payload_hash),
  CONSTRAINT ck_raw_observation_status CHECK (processing_status IN ('RECEIVED','NORMALIZED','REJECTED','QUARANTINED')),
  CONSTRAINT ck_raw_observation_payload_hash CHECK (payload_hash ~ '^[a-f0-9]{64}$')
);
  `);
}

export async function down({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
DROP TABLE IF EXISTS intelligence.raw_observation CASCADE;
DROP TABLE IF EXISTS intelligence.agent_run CASCADE;
DROP TABLE IF EXISTS intelligence.ai_agent CASCADE;
  `);
}
