import type { MigrationContext } from '../migration.types';

/**
 * Models qualitative intelligence as claims backed by quoted evidence.
 *
 * `claim_type` is what keeps an AI inference from being presented as an
 * established fact, and `claim_evidence` stores the exact excerpt used so a
 * reviewer never has to trust a URL that may change or disappear.
 */
export async function up({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
CREATE TABLE intelligence.economic_entity (
  economic_entity_id uuid NOT NULL PRIMARY KEY,
  parent_entity_id uuid,
  classification_item_id uuid,
  geographic_unit_id uuid,
  entity_type varchar(40) NOT NULL,
  legal_name varchar(250) NOT NULL,
  short_name varchar(120),
  tax_identifier varchar(50),
  country_code char(2) NOT NULL,
  economic_relevance varchar(20),
  is_active boolean NOT NULL,
  CONSTRAINT uq_economic_entity_entity_type_legal_name_country_code UNIQUE (entity_type, legal_name, country_code),
  CONSTRAINT ck_economic_entity_type CHECK (entity_type IN ('COMPANY','BUSINESS_GROUP','FINANCIAL_INSTITUTION','PUBLIC_INSTITUTION','SECURITIES_ISSUER','PERSON')),
  CONSTRAINT ck_economic_entity_relevance CHECK (economic_relevance IS NULL OR economic_relevance IN ('CRITICAL','HIGH','MEDIUM','LOW'))
);

CREATE TABLE intelligence.entity_alias (
  entity_alias_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  economic_entity_id uuid NOT NULL,
  alias varchar(250) NOT NULL,
  normalized_alias varchar(250) NOT NULL,
  alias_type varchar(30) NOT NULL,
  CONSTRAINT uq_entity_alias_normalized_alias_economic_entity_id UNIQUE (normalized_alias, economic_entity_id),
  CONSTRAINT ck_entity_alias_type CHECK (alias_type IN ('TRADE_NAME','LEGAL_NAME','ACRONYM','FORMER_NAME','BRAND','MISSPELLING'))
);

CREATE TABLE intelligence.fact_claim (
  fact_claim_id uuid NOT NULL PRIMARY KEY,
  agent_run_id uuid NOT NULL,
  raw_observation_id bigint,
  statistical_domain_id uuid,
  geographic_unit_id uuid,
  economic_entity_id uuid,
  superseded_by_claim_id uuid,
  claim_type varchar(40) NOT NULL,
  assertion text NOT NULL,
  event_date date,
  published_at timestamptz,
  time_horizon varchar(30),
  impact_level varchar(20),
  probability numeric(5,4),
  confidence_level varchar(20) NOT NULL,
  confidence_score numeric(5,4),
  status varchar(30) NOT NULL,
  content_hash char(64) NOT NULL,
  created_at timestamptz NOT NULL,
  CONSTRAINT ck_fact_claim_type CHECK (claim_type IN ('FACT','INDICATOR_READING','ESTIMATE','OPINION','FORECAST','AI_INFERENCE','RISK','OPPORTUNITY','THREAT','TREND','RECOMMENDATION')),
  CONSTRAINT ck_fact_claim_status CHECK (status IN ('DRAFT','PENDING_REVIEW','PUBLISHED','REJECTED','SUPERSEDED')),
  CONSTRAINT ck_fact_claim_confidence_level CHECK (confidence_level IN ('VERY_LOW','LOW','MEDIUM','HIGH','VERY_HIGH')),
  CONSTRAINT ck_fact_claim_confidence_score CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)),
  CONSTRAINT ck_fact_claim_probability CHECK (probability IS NULL OR (probability >= 0 AND probability <= 1)),
  CONSTRAINT ck_fact_claim_impact_level CHECK (impact_level IS NULL OR impact_level IN ('CRITICAL','HIGH','MEDIUM','LOW','NEGLIGIBLE')),
  CONSTRAINT ck_fact_claim_time_horizon CHECK (time_horizon IS NULL OR time_horizon IN ('IMMEDIATE','SHORT_TERM','MEDIUM_TERM','LONG_TERM','STRUCTURAL')),
  CONSTRAINT ck_fact_claim_content_hash CHECK (content_hash ~ '^[a-f0-9]{64}$'),
  CONSTRAINT ck_fact_claim_supersede_self CHECK (superseded_by_claim_id IS NULL OR superseded_by_claim_id <> fact_claim_id)
);

CREATE TABLE intelligence.claim_evidence (
  claim_evidence_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  fact_claim_id uuid NOT NULL,
  source_artifact_id uuid NOT NULL,
  excerpt text NOT NULL,
  excerpt_hash char(64) NOT NULL,
  locator text,
  retrieved_at timestamptz NOT NULL,
  CONSTRAINT uq_claim_evidence_fact_claim_id_excerpt_hash UNIQUE (fact_claim_id, excerpt_hash),
  CONSTRAINT ck_claim_evidence_excerpt_hash CHECK (excerpt_hash ~ '^[a-f0-9]{64}$')
);

CREATE TABLE intelligence.entity_mention (
  entity_mention_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  fact_claim_id uuid NOT NULL,
  economic_entity_id uuid,
  mention_text varchar(250) NOT NULL,
  resolution_method varchar(30) NOT NULL,
  resolution_confidence numeric(5,4),
  CONSTRAINT ck_entity_mention_resolution_method CHECK (resolution_method IN ('EXACT_ALIAS','NORMALIZED_ALIAS','MANUAL','UNRESOLVED')),
  CONSTRAINT ck_entity_mention_resolution_confidence CHECK (resolution_confidence IS NULL OR (resolution_confidence >= 0 AND resolution_confidence <= 1)),
  CONSTRAINT ck_entity_mention_resolved_requires_entity CHECK (resolution_method = 'UNRESOLVED' OR economic_entity_id IS NOT NULL)
);
  `);
}

export async function down({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
DROP TABLE IF EXISTS intelligence.entity_mention CASCADE;
DROP TABLE IF EXISTS intelligence.claim_evidence CASCADE;
DROP TABLE IF EXISTS intelligence.fact_claim CASCADE;
DROP TABLE IF EXISTS intelligence.entity_alias CASCADE;
DROP TABLE IF EXISTS intelligence.economic_entity CASCADE;
  `);
}
