import type { MigrationContext } from '../migration.types';

/**
 * Records every sensitive action against the datacenter.
 *
 * The table is append-only by privilege, not by convention: migration 0023
 * grants INSERT and SELECT to the runtime role and never UPDATE or DELETE, so
 * an application defect cannot rewrite the institutional trail.
 */
export async function up({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
CREATE TABLE audit.audit_log (
  audit_log_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  actor_organization_id uuid,
  actor_subject varchar(200) NOT NULL,
  actor_roles varchar(200) NOT NULL,
  action varchar(80) NOT NULL,
  entity_type varchar(80) NOT NULL,
  entity_reference varchar(120),
  outcome varchar(20) NOT NULL,
  correlation_id varchar(128) NOT NULL,
  client_context varchar(100),
  details_json jsonb NOT NULL,
  occurred_at timestamptz NOT NULL,
  CONSTRAINT ck_audit_log_outcome CHECK (outcome IN ('SUCCESS','FAILURE'))
);
  `);
}

export async function down({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
DROP TABLE IF EXISTS audit.audit_log CASCADE;
  `);
}
