import type { MigrationContext } from '../migration.types';

/**
 * Groups the same story reported by several outlets without discarding any of them.
 *
 * A syndicated wire item reappears in many newspapers with a changed headline.
 * Clustering links those reports so an analyst sees one event with several
 * sources, while every original claim, its evidence and its provenance survive.
 */
export async function up({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
CREATE TABLE intelligence.document_cluster (
  document_cluster_id uuid NOT NULL PRIMARY KEY,
  representative_claim_id uuid,
  cluster_fingerprint char(64) NOT NULL UNIQUE,
  member_count integer NOT NULL,
  first_seen_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  CONSTRAINT ck_document_cluster_member_count CHECK (member_count >= 0),
  CONSTRAINT ck_document_cluster_fingerprint CHECK (cluster_fingerprint ~ '^[a-f0-9]{64}$'),
  CONSTRAINT ck_document_cluster_seen_order CHECK (last_seen_at >= first_seen_at)
);

CREATE TABLE intelligence.claim_cluster_member (
  claim_cluster_member_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  document_cluster_id uuid NOT NULL,
  fact_claim_id uuid NOT NULL,
  similarity numeric(5,4) NOT NULL,
  joined_at timestamptz NOT NULL,
  CONSTRAINT uq_claim_cluster_member_cluster_claim UNIQUE (document_cluster_id, fact_claim_id),
  CONSTRAINT ck_claim_cluster_member_similarity CHECK (similarity >= 0 AND similarity <= 1)
);

ALTER TABLE intelligence.document_cluster
  ADD CONSTRAINT fk_document_cluster_representative_claim_id
  FOREIGN KEY (representative_claim_id) REFERENCES intelligence.fact_claim (fact_claim_id)
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE intelligence.claim_cluster_member
  ADD CONSTRAINT fk_claim_cluster_member_document_cluster_id
  FOREIGN KEY (document_cluster_id) REFERENCES intelligence.document_cluster (document_cluster_id)
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE intelligence.claim_cluster_member
  ADD CONSTRAINT fk_claim_cluster_member_fact_claim_id
  FOREIGN KEY (fact_claim_id) REFERENCES intelligence.fact_claim (fact_claim_id)
  ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE INDEX ix_document_cluster_representative_claim_id ON intelligence.document_cluster (representative_claim_id);
CREATE INDEX ix_claim_cluster_member_fact_claim_id ON intelligence.claim_cluster_member (fact_claim_id);
CREATE INDEX ix_document_cluster_last_seen_at ON intelligence.document_cluster (last_seen_at DESC);
  `);
}

export async function down({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
DROP INDEX IF EXISTS intelligence.ix_document_cluster_last_seen_at;
DROP INDEX IF EXISTS intelligence.ix_claim_cluster_member_fact_claim_id;
DROP INDEX IF EXISTS intelligence.ix_document_cluster_representative_claim_id;
DROP TABLE IF EXISTS intelligence.claim_cluster_member CASCADE;
DROP TABLE IF EXISTS intelligence.document_cluster CASCADE;
  `);
}
