import type { MigrationContext } from '../migration.types';

/**
 * Opens a register for how the observatory runs, not for what it measures.
 *
 * Everything the datacenter knows about Bolivia already has a home: the raw
 * observation, the claim, the revision, the audit entry. What none of them
 * records is the operation itself — whether a source that promised a daily
 * figure delivered one, whether the load that arrived was ever published,
 * whether the catalogue this deployment is supposed to carry is the catalogue
 * it actually carries. Those answers were being inferred, and every inference
 * had the same failure mode: absence of evidence read as good news.
 *
 * `operations` is deliberately separate from the domain schemas. A row here
 * describes a process; a row there describes the country. Mixing them would
 * make an operational retention policy a policy about economic history, which
 * is immutable and must stay that way.
 *
 * Three invariants are worth naming because the portal depends on them:
 *
 * 1. `seed_application` is unique per (database, package, version). A package
 *    that claims to be applied twice to the same database with two different
 *    checksums is a conflict the ledger can state, not an update it absorbs.
 * 2. `seed_run.request_fingerprint` is unique, so a resubmitted reconciliation
 *    returns the run that already exists rather than starting a second one.
 * 3. `ingestion_event` is append-only by intent and carries its counters per
 *    stage, so «collected» and «published» can disagree — which is exactly the
 *    state a green workflow was hiding.
 *
 * The change to `quality_lineage.quality_assessment` is additive and nullable.
 * Assessments recorded before today were never measured against a population,
 * and this migration does not invent one for them.
 *
 * The SQL is written here rather than in a `migration-sql` module because the
 * physical-model gate parses the migration files themselves: a table declared
 * anywhere else is invisible to the drift check that is supposed to catch it.
 */
export async function up({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
CREATE SCHEMA IF NOT EXISTS operations;
  `);

  await context.sequelize.query(`
CREATE TABLE operations.seed_application (
  seed_application_id uuid NOT NULL PRIMARY KEY,
  database_identity varchar(200) NOT NULL,
  environment_id varchar(60) NOT NULL,
  package_code varchar(80) NOT NULL,
  package_version varchar(40) NOT NULL,
  checksum char(64) NOT NULL,
  applied_commit varchar(60),
  applied_at timestamptz NOT NULL,
  summary_json jsonb NOT NULL,
  CONSTRAINT uq_seed_application_target UNIQUE (database_identity, package_code, package_version),
  CONSTRAINT ck_seed_application_checksum CHECK (checksum ~ '^[a-f0-9]{64}$')
);

CREATE TABLE operations.seed_run (
  seed_run_id uuid NOT NULL PRIMARY KEY,
  package_code varchar(80) NOT NULL,
  package_version varchar(40) NOT NULL,
  operation varchar(20) NOT NULL,
  attempt_no integer NOT NULL,
  actor_subject varchar(200) NOT NULL,
  environment_id varchar(60) NOT NULL,
  database_identity varchar(200) NOT NULL,
  status varchar(20) NOT NULL,
  request_fingerprint char(64) NOT NULL UNIQUE,
  started_at timestamptz NOT NULL,
  heartbeat_at timestamptz NOT NULL,
  completed_at timestamptz,
  error_summary varchar(500),
  checkpoint_json jsonb,
  counters_json jsonb NOT NULL,
  CONSTRAINT ck_seed_run_attempt CHECK (attempt_no > 0),
  CONSTRAINT ck_seed_run_operation CHECK (operation IN ('VALIDATION', 'RECONCILIATION')),
  CONSTRAINT ck_seed_run_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED', 'ABANDONED')),
  CONSTRAINT ck_seed_run_completion CHECK (completed_at IS NULL OR completed_at >= started_at),
  CONSTRAINT ck_seed_run_fingerprint CHECK (request_fingerprint ~ '^[a-f0-9]{64}$')
);

CREATE TABLE operations.source_expectation (
  source_expectation_id uuid NOT NULL PRIMARY KEY,
  source_id uuid NOT NULL UNIQUE,
  cadence varchar(20) NOT NULL,
  expected_interval_hours integer,
  tolerance_hours integer NOT NULL,
  time_zone varchar(60) NOT NULL,
  is_active boolean NOT NULL,
  CONSTRAINT ck_source_expectation_cadence CHECK (cadence IN ('CONTINUOUS', 'PERIODIC', 'HISTORICAL')),
  CONSTRAINT ck_source_expectation_interval CHECK ((cadence = 'HISTORICAL') = (expected_interval_hours IS NULL)),
  CONSTRAINT ck_source_expectation_tolerance CHECK (tolerance_hours >= 0)
);

CREATE TABLE operations.ingestion_event (
  ingestion_event_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  correlation_id varchar(128) NOT NULL,
  agent_run_id uuid,
  source_id uuid,
  stage varchar(30) NOT NULL,
  outcome varchar(20) NOT NULL,
  occurred_at timestamptz NOT NULL,
  duration_ms integer,
  artifact_reference varchar(500),
  artifact_sha256 char(64),
  records_received bigint NOT NULL,
  records_accepted bigint NOT NULL,
  records_rejected bigint NOT NULL,
  records_skipped bigint NOT NULL,
  reason varchar(200),
  details_json jsonb,
  CONSTRAINT ck_ingestion_event_stage CHECK (stage IN ('COLLECTION', 'VALIDATION', 'DELIVERY', 'PERSISTENCE', 'REVIEW', 'PUBLICATION')),
  CONSTRAINT ck_ingestion_event_outcome CHECK (outcome IN ('SUCCEEDED', 'PARTIAL', 'FAILED', 'NO_CHANGES', 'SKIPPED')),
  CONSTRAINT ck_ingestion_event_counts CHECK (records_received >= 0 AND records_accepted >= 0 AND records_rejected >= 0 AND records_skipped >= 0),
  CONSTRAINT ck_ingestion_event_sha CHECK (artifact_sha256 IS NULL OR artifact_sha256 ~ '^[a-f0-9]{64}$')
);

CREATE TABLE operations.read_model_publication (
  read_model_publication_id uuid NOT NULL PRIMARY KEY,
  dataset_code varchar(80) NOT NULL UNIQUE,
  status varchar(20) NOT NULL,
  source_cutoff_at timestamptz,
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  last_error varchar(500),
  CONSTRAINT ck_read_model_publication_status CHECK (status IN ('PUBLISHED', 'PENDING', 'FAILED', 'UNKNOWN'))
);

CREATE TABLE operations.export_request (
  export_request_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  request_id varchar(64) NOT NULL,
  dataset_code varchar(40) NOT NULL,
  export_format varchar(10) NOT NULL,
  status varchar(20) NOT NULL,
  filters_json jsonb NOT NULL,
  row_count bigint,
  byte_count bigint,
  duration_ms integer,
  truncated boolean NOT NULL,
  occurred_at timestamptz NOT NULL,
  error_code varchar(60),
  CONSTRAINT uq_export_request_stage UNIQUE (request_id, status),
  CONSTRAINT ck_export_request_status CHECK (status IN ('REQUESTED', 'GENERATED', 'FAILED')),
  CONSTRAINT ck_export_request_format CHECK (export_format IN ('csv', 'json')),
  CONSTRAINT ck_export_request_counts CHECK ((row_count IS NULL OR row_count >= 0) AND (byte_count IS NULL OR byte_count >= 0))
);

CREATE TABLE operations.traffic_event (
  traffic_event_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  event_key varchar(64) NOT NULL UNIQUE,
  occurred_at timestamptz NOT NULL,
  route varchar(200) NOT NULL,
  event_kind varchar(20) NOT NULL,
  device_category varchar(20) NOT NULL,
  referrer_category varchar(20) NOT NULL,
  visitor_bucket char(16) NOT NULL,
  is_robot boolean NOT NULL,
  CONSTRAINT ck_traffic_event_kind CHECK (event_kind IN ('PAGE_VIEW', 'DOWNLOAD_INTENT')),
  CONSTRAINT ck_traffic_event_device CHECK (device_category IN ('DESKTOP', 'MOBILE', 'TABLET', 'UNKNOWN')),
  CONSTRAINT ck_traffic_event_referrer CHECK (referrer_category IN ('DIRECT', 'SEARCH', 'SOCIAL', 'EXTERNAL', 'INTERNAL'))
);

CREATE TABLE operations.health_probe (
  health_probe_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  target varchar(80) NOT NULL,
  probe_type varchar(30) NOT NULL,
  observed_at timestamptz NOT NULL,
  duration_ms integer,
  outcome varchar(20) NOT NULL,
  evidence_json jsonb,
  error_summary varchar(300),
  CONSTRAINT ck_health_probe_outcome CHECK (outcome IN ('UP', 'DOWN', 'UNKNOWN')),
  CONSTRAINT ck_health_probe_type CHECK (probe_type IN ('HTTP', 'JOURNEY', 'DATASET'))
);

CREATE TABLE operations.health_incident (
  health_incident_id uuid NOT NULL PRIMARY KEY,
  target varchar(80) NOT NULL,
  status varchar(20) NOT NULL,
  cause varchar(200) NOT NULL,
  consecutive_failures integer NOT NULL,
  opened_at timestamptz NOT NULL,
  closed_at timestamptz,
  CONSTRAINT ck_health_incident_status CHECK (status IN ('OPEN', 'CLOSED')),
  CONSTRAINT ck_health_incident_closure CHECK (closed_at IS NULL OR closed_at >= opened_at),
  CONSTRAINT ck_health_incident_failures CHECK (consecutive_failures >= 0)
);

CREATE TABLE operations.alert_delivery (
  alert_delivery_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  health_incident_id uuid,
  rule_code varchar(60) NOT NULL,
  dedup_key varchar(160) NOT NULL,
  channel varchar(30) NOT NULL,
  attempt_no integer NOT NULL,
  status varchar(20) NOT NULL,
  dispatched_at timestamptz NOT NULL,
  error_summary varchar(300),
  CONSTRAINT uq_alert_delivery_attempt UNIQUE (dedup_key, channel, attempt_no),
  CONSTRAINT ck_alert_delivery_status CHECK (status IN ('PENDING', 'DELIVERED', 'FAILED', 'SUPPRESSED')),
  CONSTRAINT ck_alert_delivery_attempt CHECK (attempt_no > 0)
);
  `);

  await context.sequelize.query(`
ALTER TABLE operations.source_expectation
  ADD CONSTRAINT fk_source_expectation_source_id
  FOREIGN KEY (source_id) REFERENCES provenance.source (source_id)
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE operations.ingestion_event
  ADD CONSTRAINT fk_ingestion_event_agent_run_id
  FOREIGN KEY (agent_run_id) REFERENCES intelligence.agent_run (agent_run_id)
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE operations.ingestion_event
  ADD CONSTRAINT fk_ingestion_event_source_id
  FOREIGN KEY (source_id) REFERENCES provenance.source (source_id)
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE operations.alert_delivery
  ADD CONSTRAINT fk_alert_delivery_health_incident_id
  FOREIGN KEY (health_incident_id) REFERENCES operations.health_incident (health_incident_id)
  ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE INDEX ix_ingestion_event_agent_run_id ON operations.ingestion_event (agent_run_id);
CREATE INDEX ix_ingestion_event_source_id ON operations.ingestion_event (source_id);
CREATE INDEX ix_ingestion_event_occurred_at ON operations.ingestion_event (occurred_at DESC, ingestion_event_id DESC);
CREATE INDEX ix_ingestion_event_correlation ON operations.ingestion_event (correlation_id);
CREATE INDEX ix_ingestion_event_stage_outcome ON operations.ingestion_event (stage, outcome, occurred_at DESC);
CREATE INDEX ix_alert_delivery_health_incident_id ON operations.alert_delivery (health_incident_id);
CREATE INDEX ix_source_expectation_source_id ON operations.source_expectation (source_id);
CREATE INDEX ix_seed_run_started_at ON operations.seed_run (started_at DESC, seed_run_id DESC);
CREATE INDEX ix_seed_run_status ON operations.seed_run (status, heartbeat_at DESC);
CREATE INDEX ix_seed_application_package ON operations.seed_application (package_code, package_version);
CREATE INDEX ix_export_request_occurred_at ON operations.export_request (occurred_at DESC, export_request_id DESC);
CREATE INDEX ix_export_request_dataset ON operations.export_request (dataset_code, occurred_at DESC);
CREATE INDEX ix_traffic_event_occurred_at ON operations.traffic_event (occurred_at DESC, traffic_event_id DESC);
CREATE INDEX ix_traffic_event_route ON operations.traffic_event (route, occurred_at DESC);
CREATE INDEX ix_health_probe_target_time ON operations.health_probe (target, observed_at DESC);
CREATE INDEX ix_health_incident_target_status ON operations.health_incident (target, status, opened_at DESC);
  `);

  /*
   * What an assessment now has to say before a share of it can be believed.
   *
   * `status` alone answers «did it pass», and the portal has to answer «over
   * how many, and how many could not be judged at all». Without a denominator
   * a percentage with no population reads as a hundred per cent, which is the
   * one reading this register must never produce.
   */
  await context.sequelize.query(`
ALTER TABLE quality_lineage.quality_assessment
  ADD COLUMN rule_version varchar(20);
ALTER TABLE quality_lineage.quality_assessment
  ADD COLUMN evaluation_scope varchar(120);
ALTER TABLE quality_lineage.quality_assessment
  ADD COLUMN numerator bigint;
ALTER TABLE quality_lineage.quality_assessment
  ADD COLUMN denominator bigint;
ALTER TABLE quality_lineage.quality_assessment
  ADD COLUMN not_evaluated bigint;
ALTER TABLE quality_lineage.quality_assessment
  ADD COLUMN cutoff_at timestamptz;

ALTER TABLE quality_lineage.quality_assessment
  DROP CONSTRAINT ck_quality_assessment_status;
ALTER TABLE quality_lineage.quality_assessment
  ADD CONSTRAINT ck_quality_assessment_status
  CHECK (status IN ('PASS', 'WARNING', 'FAIL', 'ERROR', 'NOT_EVALUATED', 'NOT_APPLICABLE'));
ALTER TABLE quality_lineage.quality_assessment
  ADD CONSTRAINT ck_quality_assessment_population
  CHECK (
    (numerator IS NULL AND denominator IS NULL)
    OR (numerator >= 0 AND denominator >= 0 AND numerator <= denominator)
  );

CREATE UNIQUE INDEX ux_quality_assessment_evaluation
  ON quality_lineage.quality_assessment (quality_rule_id, rule_version, evaluation_scope, cutoff_at)
  WHERE rule_version IS NOT NULL;
  `);

  /*
   * Who may read and write the operational register.
   *
   * The reader keeps the whole schema because everything in it exists to be
   * reported and none of it is confidential on its own; the writer gets the
   * DML it needs and no `CREATE`, so the runtime credential still cannot
   * change the shape of the database it writes to.
   */
  await context.sequelize.query(`
DO $$
BEGIN
  REVOKE ALL ON SCHEMA operations FROM PUBLIC;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend_writer') THEN
    REVOKE CREATE ON SCHEMA operations FROM backend_writer;
    GRANT USAGE ON SCHEMA operations TO backend_writer;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA operations TO backend_writer;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA operations TO backend_writer;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend_reader') THEN
    REVOKE CREATE ON SCHEMA operations FROM backend_reader;
    GRANT USAGE ON SCHEMA operations TO backend_reader;
    GRANT SELECT ON ALL TABLES IN SCHEMA operations TO backend_reader;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backup_operator') THEN
    GRANT USAGE ON SCHEMA operations TO backup_operator;
    GRANT SELECT ON ALL TABLES IN SCHEMA operations TO backup_operator;
  END IF;
END
$$;
  `);

  /*
   * Lets the runtime rebuild a stored copy without owning it.
   *
   * `REFRESH MATERIALIZED VIEW` requires ownership; no GRANT substitutes for
   * it. Until now the API refreshed the four expensive copies through the
   * writer, which works only where the writer happens to own the schema — and
   * fails outright on a database whose privileges match the design, which is
   * why the continuous integration run has been red since 2026-09-08 with
   * «permission denied for schema read_models» after loading every catalogue
   * correctly. The choice was between making the writer an owner, which would
   * also let it drop the copies, and giving it one function that can do
   * exactly this and nothing else.
   *
   * The name is resolved against the catalog instead of being interpolated, so
   * the only things this can refresh are materialised views that already exist
   * in `read_models`. It returns the row count so the caller never needs SELECT
   * on the copy it just rebuilt.
   */
  await context.sequelize.query(`
CREATE FUNCTION read_models.refresh_snapshot(snapshot_name text, refresh_concurrently boolean)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $function$
DECLARE
  target text;
  row_total bigint;
BEGIN
  SELECT class.relname INTO target
    FROM pg_catalog.pg_class class
    JOIN pg_catalog.pg_namespace namespace ON namespace.oid = class.relnamespace
   WHERE namespace.nspname = 'read_models'
     AND class.relkind = 'm'
     AND class.relname = snapshot_name;
  IF target IS NULL THEN
    RAISE EXCEPTION 'La copia guardada % no existe', snapshot_name;
  END IF;
  IF refresh_concurrently THEN
    EXECUTE format('REFRESH MATERIALIZED VIEW CONCURRENTLY read_models.%I', target);
  ELSE
    EXECUTE format('REFRESH MATERIALIZED VIEW read_models.%I', target);
  END IF;
  EXECUTE format('SELECT count(*) FROM read_models.%I', target) INTO row_total;
  RETURN row_total;
END;
$function$;

REVOKE ALL ON FUNCTION read_models.refresh_snapshot(text, boolean) FROM PUBLIC;
  `);

  await context.sequelize.query(`
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend_writer') THEN
    GRANT USAGE ON SCHEMA read_models TO backend_writer;
    GRANT EXECUTE ON FUNCTION read_models.refresh_snapshot(text, boolean) TO backend_writer;
  END IF;
END
$$;
  `);

  /*
   * Which migrations have run, readable by the runtime that has to respect them.
   *
   * A seed package declares the schema it needs, and refusing one on a database
   * that has not reached that migration is the check that stops a catalogue
   * being written against a table that does not exist yet. Asking the build
   * which migrations exist would answer a different question — the build always
   * has all of them — so the answer has to come from the database, and until now
   * only the migrator could read it. Read only, and the history is append-only
   * for everyone else.
   */
  await context.sequelize.query(`
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend_writer') THEN
    GRANT USAGE ON SCHEMA infrastructure TO backend_writer;
    GRANT SELECT ON infrastructure.migration_history TO backend_writer;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend_reader') THEN
    GRANT USAGE ON SCHEMA infrastructure TO backend_reader;
    GRANT SELECT ON infrastructure.migration_history TO backend_reader;
  END IF;
END
$$;
  `);

  /*
   * The reference tables an operator has to be able to see.
   *
   * Migration 0014 gave the reader a whitelist built for the public report, and
   * the administrative console asks a different question: which catalogues does
   * this deployment carry, which rule is failing, which raw items were dead
   * lettered. None of that was readable, and one consequence was already live —
   * the domain metric collector counts dead letters in
   * `intelligence.raw_observation` through the reader, so on a database whose
   * grants match the design that gauge has always failed silently and reported
   * nothing rather than a backlog.
   *
   * Everything added here is reference data or an operational counter. No
   * evidence excerpt, no organisation-scoped claim and no audit detail beyond
   * what 0025 already granted becomes visible through this.
   */
  await context.sequelize.query(`
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend_reader') THEN
    GRANT USAGE ON SCHEMA semantic TO backend_reader;
    GRANT SELECT ON TABLE
      semantic.frequency,
      semantic.unit_measure,
      semantic.geographic_unit,
      semantic.statistical_domain,
      semantic.classification,
      semantic.classification_version,
      semantic.classification_item,
      semantic.concept,
      semantic.code_list,
      semantic.code_item,
      quality_lineage.quality_dimension,
      quality_lineage.quality_rule,
      quality_lineage.indicator_relation,
      metadata.methodology,
      metadata.statistical_operation,
      metadata.data_structure,
      statistics.indicator,
      statistics.indicator_version,
      statistics.dataset_indicator,
      intelligence.raw_observation
      TO backend_reader;
  END IF;
END
$$;
  `);
}

export async function down({ context }: MigrationContext): Promise<void> {
  await context.sequelize.query(`
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend_reader') THEN
    REVOKE SELECT ON TABLE
      semantic.frequency,
      semantic.unit_measure,
      semantic.geographic_unit,
      semantic.statistical_domain,
      semantic.classification,
      semantic.classification_version,
      semantic.classification_item,
      semantic.concept,
      semantic.code_list,
      semantic.code_item,
      quality_lineage.quality_dimension,
      quality_lineage.quality_rule,
      quality_lineage.indicator_relation,
      metadata.methodology,
      metadata.statistical_operation,
      metadata.data_structure,
      statistics.indicator,
      statistics.indicator_version,
      statistics.dataset_indicator,
      intelligence.raw_observation
      FROM backend_reader;
    REVOKE USAGE ON SCHEMA semantic FROM backend_reader;
    REVOKE SELECT ON infrastructure.migration_history FROM backend_reader;
    REVOKE USAGE ON SCHEMA infrastructure FROM backend_reader;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'backend_writer') THEN
    REVOKE SELECT ON infrastructure.migration_history FROM backend_writer;
    REVOKE USAGE ON SCHEMA infrastructure FROM backend_writer;
  END IF;
END
$$;
  `);
  await context.sequelize.query(`
DROP FUNCTION IF EXISTS read_models.refresh_snapshot(text, boolean);
  `);
  await context.sequelize.query(`
DROP INDEX IF EXISTS quality_lineage.ux_quality_assessment_evaluation;
ALTER TABLE quality_lineage.quality_assessment
  DROP CONSTRAINT IF EXISTS ck_quality_assessment_population;
ALTER TABLE quality_lineage.quality_assessment
  DROP CONSTRAINT IF EXISTS ck_quality_assessment_status;
ALTER TABLE quality_lineage.quality_assessment
  ADD CONSTRAINT ck_quality_assessment_status
  CHECK (status IN ('PASS', 'WARNING', 'FAIL', 'ERROR'));
ALTER TABLE quality_lineage.quality_assessment DROP COLUMN IF EXISTS cutoff_at;
ALTER TABLE quality_lineage.quality_assessment DROP COLUMN IF EXISTS not_evaluated;
ALTER TABLE quality_lineage.quality_assessment DROP COLUMN IF EXISTS denominator;
ALTER TABLE quality_lineage.quality_assessment DROP COLUMN IF EXISTS numerator;
ALTER TABLE quality_lineage.quality_assessment DROP COLUMN IF EXISTS evaluation_scope;
ALTER TABLE quality_lineage.quality_assessment DROP COLUMN IF EXISTS rule_version;
  `);
  await context.sequelize.query(`
DROP SCHEMA IF EXISTS operations CASCADE;
  `);
}
