module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  roots: [
    '<rootDir>/src/common',
    '<rootDir>/src/config',
    '<rootDir>/src/database',
    '<rootDir>/src/modules/governance',
    '<rootDir>/src/modules/ingestion',
    '<rootDir>/src/modules/query',
  ],
  testRegex: '.*\\.spec\\.ts$',
  transform: { '^.+\\.(t|j)s$': ['ts-jest', { tsconfig: 'tsconfig.json' }] },
  collectCoverageFrom: [
    'src/common/**/*.ts',
    'src/config/**/*.ts',
    'src/database/database-connections.ts',
    'src/modules/governance/**/*.ts',
    'src/modules/ingestion/**/*.ts',
    'src/modules/provenance/**/*.ts',
    'src/modules/quality/**/*.ts',
    'src/modules/query/**/*.ts',
    '!src/**/*.module.ts',
    '!src/**/*.controller.ts',
  ],
  coverageDirectory: 'artifacts/coverage',
  testEnvironment: 'node',
  clearMocks: true,
};
