/**
 * The annual macro view exactly as migration 0055 wrote it.
 *
 * A snapshot, never edited: a later change to how a series is filed is a
 * later migration with its own copy, so rolling forward and back always
 * replays the definition that step actually applied.
 */

export const annualView = `
CREATE VIEW read_models.macro_indicator_annual AS
WITH published AS (
  SELECT
    indicator_code,
    max(indicator_name)   AS indicator_name,
    period,
    unit,
    max(publisher)        AS publisher,
    max(source_url)       AS source_url,
    max(evidence_sha256)  AS evidence_sha256,
    max(event_date)       AS period_end,
    avg(value)            AS value,
    'PUBLISHED_ANNUAL'    AS statistic
  FROM read_models.economic_indicator_reading
  WHERE status = 'PUBLISHED'
    AND NOT superseded
    AND frequency = 'ANNUAL'
    AND period IS NOT NULL
  GROUP BY indicator_code, period, unit
),
-- The unit is quoted every calendar day, so its year is closed by the last day
-- that has actually happened, never by one the bank published in advance.
year_end AS (
  SELECT DISTINCT ON (indicator_code, to_char(event_date, 'YYYY'))
    indicator_code,
    'Unidad de Fomento de Vivienda'::text AS indicator_name,
    to_char(event_date, 'YYYY')           AS period,
    unit,
    publisher,
    source_url,
    evidence_sha256,
    event_date                            AS period_end,
    value,
    CASE
      WHEN to_char(event_date, 'YYYY') = to_char(current_date, 'YYYY') THEN 'YEAR_TO_DATE'
      ELSE 'YEAR_END'
    END                                   AS statistic
  FROM read_models.economic_indicator_reading
  WHERE status = 'PUBLISHED'
    AND NOT superseded
    AND frequency = 'DAILY'
    AND indicator_code = 'UFV_BOB'
    AND event_date IS NOT NULL
    AND event_date <= current_date
  ORDER BY indicator_code, to_char(event_date, 'YYYY'), event_date DESC, value DESC
),
combined AS (
  SELECT * FROM published
  UNION ALL
  SELECT * FROM year_end
),
classified AS (
  SELECT
    combined.*,
    CASE indicator_code
    WHEN 'ADULT_LITERACY_PCT' THEN 'SOCIAL'
    WHEN 'AGRICULTURAL_EXPORTS_PCT' THEN 'EXTERNO'
    WHEN 'AGRICULTURE_GROWTH_PCT' THEN 'SECTORIAL'
    WHEN 'AGRICULTURE_VALUE_ADDED_PCT_GDP' THEN 'SECTORIAL'
    WHEN 'ATMS_PER_100K_ADULTS' THEN 'FINANCIERO'
    WHEN 'BANK_CAPITAL_TO_ASSETS_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_CAPITAL_TO_TOTAL_ASSETS_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_CONCENTRATION_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_COST_TO_INCOME_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_CREDIT_TO_DEPOSITS_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_DEPOSITS_PCT_GDP' THEN 'FINANCIERO'
    WHEN 'BANK_LENDING_DEPOSIT_SPREAD_PCT' THEN 'MONETARIO'
    WHEN 'BANK_LIQUID_RESERVES_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_NET_INTEREST_MARGIN_PCT' THEN 'MONETARIO'
    WHEN 'BANK_NONPERFORMING_LOANS_GFDD_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_REGULATORY_CAPITAL_PCT_RWA' THEN 'FINANCIERO'
    WHEN 'BANK_RETURN_ON_ASSETS_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_RETURN_ON_EQUITY_PCT' THEN 'FINANCIERO'
    WHEN 'BANK_Z_SCORE' THEN 'FINANCIERO'
    WHEN 'BASIC_SANITATION_ACCESS_PCT' THEN 'SOCIAL'
    WHEN 'BASIC_WATER_ACCESS_PCT' THEN 'SOCIAL'
    WHEN 'BOP_EXPORTS_USD' THEN 'EXTERNO'
    WHEN 'BOP_IMPORTS_USD' THEN 'EXTERNO'
    WHEN 'BROAD_MONEY_GROWTH_PCT' THEN 'MONETARIO'
    WHEN 'BROAD_MONEY_PCT_GDP' THEN 'MONETARIO'
    WHEN 'CENTRAL_BANK_ASSETS_PCT_GDP' THEN 'MONETARIO'
    WHEN 'CHILD_STUNTING_PCT' THEN 'SOCIAL'
    WHEN 'COMMERCIAL_BANK_BRANCHES_PER_100K' THEN 'FINANCIERO'
    WHEN 'CONTROL_OF_CORRUPTION_SCORE' THEN 'INSTITUCIONAL'
    WHEN 'CORRUPTION_PERCEPTIONS_INDEX' THEN 'INSTITUCIONAL'
    WHEN 'CPIA_PUBLIC_SECTOR_SCORE' THEN 'INSTITUCIONAL'
    WHEN 'CPI_INDEX' THEN 'PRECIOS'
    WHEN 'CPI_INFLATION_ANNUAL_PCT' THEN 'PRECIOS'
    WHEN 'CREDIT_TO_GOVERNMENT_PCT_GDP' THEN 'MONETARIO'
    WHEN 'CURRENT_ACCOUNT_PCT_GDP' THEN 'EXTERNO'
    WHEN 'CURRENT_ACCOUNT_USD' THEN 'EXTERNO'
    WHEN 'DEBT_SERVICE_PCT_EXPORTS' THEN 'DEUDA'
    WHEN 'DEBT_TO_IBRD_USD' THEN 'DEUDA'
    WHEN 'DEBT_TO_IDA_USD' THEN 'DEUDA'
    WHEN 'DEBT_TO_WORLD_BANK_USD' THEN 'DEUDA'
    WHEN 'DEPOSIT_MONEY_BANK_ASSETS_PCT_GDP' THEN 'FINANCIERO'
    WHEN 'DEPOSIT_RATE_PCT' THEN 'MONETARIO'
    WHEN 'DOMESTIC_CREDIT_FINANCIAL_SECTOR_PCT_GDP' THEN 'FINANCIERO'
    WHEN 'EDUCATION_SPENDING_PCT_GDP' THEN 'SOCIAL'
    WHEN 'ELECTRICITY_ACCESS_PCT' THEN 'SOCIAL'
    WHEN 'EMPLOYMENT_AGRICULTURE_PCT' THEN 'SOCIAL'
    WHEN 'EMPLOYMENT_INDUSTRY_PCT' THEN 'SOCIAL'
    WHEN 'EMPLOYMENT_SERVICES_PCT' THEN 'SOCIAL'
    WHEN 'ENERGY_USE_PER_CAPITA' THEN 'SECTORIAL'
    WHEN 'EXPORTS_GOODS_SERVICES_USD' THEN 'EXTERNO'
    WHEN 'EXPORTS_PCT_GDP' THEN 'EXTERNO'
    WHEN 'EXTERNAL_DEBT_PCT_GNI' THEN 'DEUDA'
    WHEN 'EXTERNAL_DEBT_USD' THEN 'DEUDA'
    WHEN 'EXTREME_POVERTY_PCT' THEN 'SOCIAL'
    WHEN 'FDI_NET_INFLOWS_PCT_GDP' THEN 'EXTERNO'
    WHEN 'FDI_NET_INFLOWS_USD' THEN 'EXTERNO'
    WHEN 'FERTILITY_RATE_BIRTHS' THEN 'SOCIAL'
    WHEN 'FINANCIAL_SYSTEM_DEPOSITS_PCT_GDP' THEN 'FINANCIERO'
    WHEN 'FOOD_PRODUCTION_INDEX' THEN 'SECTORIAL'
    WHEN 'FOREST_RENTS_PCT_GDP' THEN 'RECURSOS'
    WHEN 'FUEL_EXPORTS_PCT' THEN 'EXTERNO'
    WHEN 'GDP_CURRENT_USD' THEN 'ACTIVIDAD'
    WHEN 'GDP_DEFLATOR_PCT' THEN 'PRECIOS'
    WHEN 'GDP_GROWTH_ANNUAL_PCT' THEN 'ACTIVIDAD'
    WHEN 'GDP_PER_CAPITA_GROWTH_PCT' THEN 'ACTIVIDAD'
    WHEN 'GDP_PER_CAPITA_USD' THEN 'ACTIVIDAD'
    WHEN 'GINI_INDEX' THEN 'SOCIAL'
    WHEN 'GOVERNMENT_CONSUMPTION_PCT_GDP' THEN 'ACTIVIDAD'
    WHEN 'GOVERNMENT_EFFECTIVENESS_SCORE' THEN 'INSTITUCIONAL'
    WHEN 'GROSS_CAPITAL_FORMATION_PCT_GDP' THEN 'ACTIVIDAD'
    WHEN 'GROSS_NATIONAL_INCOME_USD' THEN 'ACTIVIDAD'
    WHEN 'GROSS_NATIONAL_SAVINGS_PCT_GDP' THEN 'ACTIVIDAD'
    WHEN 'HEALTH_SPENDING_PCT_GDP' THEN 'SOCIAL'
    WHEN 'HIGH_TECH_EXPORTS_PCT' THEN 'ACTIVIDAD'
    WHEN 'HOUSEHOLD_CONSUMPTION_PCT_GDP' THEN 'ACTIVIDAD'
    WHEN 'HUMAN_DEVELOPMENT_INDEX' THEN 'SOCIAL'
    WHEN 'IMPORTS_GOODS_SERVICES_USD' THEN 'EXTERNO'
    WHEN 'IMPORTS_PCT_GDP' THEN 'EXTERNO'
    WHEN 'INCOME_SHARE_HIGHEST_10_PCT' THEN 'SOCIAL'
    WHEN 'INCOME_SHARE_LOWEST_20_PCT' THEN 'SOCIAL'
    WHEN 'INDUSTRY_GROWTH_PCT' THEN 'SECTORIAL'
    WHEN 'INDUSTRY_VALUE_ADDED_PCT_GDP' THEN 'SECTORIAL'
    WHEN 'INFANT_MORTALITY_PER_1000' THEN 'SOCIAL'
    WHEN 'INTENTIONAL_HOMICIDES_PER_100K' THEN 'SOCIAL'
    WHEN 'INTEREST_RATE_SPREAD_PCT' THEN 'MONETARIO'
    WHEN 'INTERNATIONAL_RESERVES_USD' THEN 'EXTERNO'
    WHEN 'INTERNET_USERS_PCT' THEN 'SOCIAL'
    WHEN 'LABOUR_PARTICIPATION_PCT' THEN 'SOCIAL'
    WHEN 'LENDING_RATE_PCT' THEN 'MONETARIO'
    WHEN 'LIFE_EXPECTANCY_YEARS' THEN 'SOCIAL'
    WHEN 'LIQUID_ASSETS_TO_DEPOSITS_PCT' THEN 'FINANCIERO'
    WHEN 'LIQUID_LIABILITIES_PCT_GDP' THEN 'MONETARIO'
    WHEN 'LONG_TERM_EXTERNAL_DEBT_USD' THEN 'DEUDA'
    WHEN 'MANUFACTURING_VALUE_ADDED_PCT_GDP' THEN 'SECTORIAL'
    WHEN 'MATERNAL_MORTALITY_PER_100K' THEN 'SOCIAL'
    WHEN 'MERCHANDISE_EXPORTS_USD' THEN 'EXTERNO'
    WHEN 'MERCHANDISE_IMPORTS_USD' THEN 'EXTERNO'
    WHEN 'MINERAL_RENTS_PCT_GDP' THEN 'RECURSOS'
    WHEN 'MOBILE_SUBSCRIPTIONS' THEN 'SECTORIAL'
    WHEN 'NATURAL_GAS_RENTS_PCT_GDP' THEN 'RECURSOS'
    WHEN 'NONBANK_FINANCIAL_ASSETS_PCT_GDP' THEN 'FINANCIERO'
    WHEN 'NONPERFORMING_LOANS_PCT' THEN 'FINANCIERO'
    WHEN 'OFFICIAL_EXCHANGE_RATE_BOB_USD' THEN 'CAMBIARIO'
    WHEN 'OIL_RENTS_PCT_GDP' THEN 'RECURSOS'
    WHEN 'ORES_METALS_EXPORTS_PCT' THEN 'EXTERNO'
    WHEN 'POLITICAL_REGIME_CLASSIFICATION' THEN 'INSTITUCIONAL'
    WHEN 'POLITICAL_STABILITY_SCORE' THEN 'INSTITUCIONAL'
    WHEN 'POPULATION_TOTAL' THEN 'SOCIAL'
    WHEN 'POVERTY_GAP_PCT' THEN 'SOCIAL'
    WHEN 'PPP_CONVERSION_FACTOR' THEN 'CAMBIARIO'
    WHEN 'PRIMARY_ENROLMENT_PCT' THEN 'SOCIAL'
    WHEN 'PRIVATE_CREDIT_BANKS_AND_OFI_PCT_GDP' THEN 'FINANCIERO'
    WHEN 'PRIVATE_CREDIT_BY_BANKS_PCT_GDP' THEN 'FINANCIERO'
    WHEN 'PRIVATE_CREDIT_PCT_GDP' THEN 'FINANCIERO'
    WHEN 'PRIVATE_NONGUARANTEED_DEBT_USD' THEN 'DEUDA'
    WHEN 'PROVISIONS_TO_NONPERFORMING_LOANS_PCT' THEN 'FINANCIERO'
    WHEN 'PUBLIC_DEBT_SERVICE_PCT_EXPORTS' THEN 'DEUDA'
    WHEN 'PUBLIC_GUARANTEED_DEBT_USD' THEN 'DEUDA'
    WHEN 'REAL_EFFECTIVE_EXCHANGE_RATE' THEN 'CAMBIARIO'
    WHEN 'REAL_INTEREST_RATE_PCT' THEN 'MONETARIO'
    WHEN 'REGULATORY_QUALITY_SCORE' THEN 'INSTITUCIONAL'
    WHEN 'REMITTANCES_PCT_GDP' THEN 'EXTERNO'
    WHEN 'REMITTANCES_USD' THEN 'EXTERNO'
    WHEN 'RESERVES_IN_IMPORT_MONTHS' THEN 'EXTERNO'
    WHEN 'RESERVES_TO_EXTERNAL_DEBT_PCT' THEN 'DEUDA'
    WHEN 'RISK_PREMIUM_ON_LENDING_PCT' THEN 'MONETARIO'
    WHEN 'RULE_OF_LAW_SCORE' THEN 'INSTITUCIONAL'
    WHEN 'SECONDARY_ENROLMENT_PCT' THEN 'SOCIAL'
    WHEN 'SERVICES_GROWTH_PCT' THEN 'SECTORIAL'
    WHEN 'SERVICES_VALUE_ADDED_PCT_GDP' THEN 'SECTORIAL'
    WHEN 'SHORT_TERM_EXTERNAL_DEBT_USD' THEN 'DEUDA'
    WHEN 'SOVEREIGN_BOND_NET_FLOWS_USD' THEN 'DEUDA'
    WHEN 'STATE_CAPACITY_INDEX' THEN 'INSTITUCIONAL'
    WHEN 'TERMS_OF_TRADE_INDEX' THEN 'EXTERNO'
    WHEN 'TOTAL_DEBT_SERVICE_USD' THEN 'DEUDA'
    WHEN 'TOTAL_NATURAL_RESOURCE_RENTS_PCT_GDP' THEN 'RECURSOS'
    WHEN 'TRADE_BALANCE_PCT_GDP' THEN 'ACTIVIDAD'
    WHEN 'UFV_BOB' THEN 'PRECIOS'
    WHEN 'UNDER_FIVE_MORTALITY_PER_1000' THEN 'SOCIAL'
    WHEN 'UNEMPLOYMENT_PCT' THEN 'SOCIAL'
    WHEN 'URBAN_POPULATION_PCT' THEN 'SOCIAL'
    WHEN 'VDEM_HUMAN_RIGHTS_INDEX' THEN 'INSTITUCIONAL'
    WHEN 'VDEM_RULE_OF_LAW_INDEX' THEN 'INSTITUCIONAL'
    WHEN 'VOICE_AND_ACCOUNTABILITY_SCORE' THEN 'INSTITUCIONAL'
    WHEN 'VULNERABLE_EMPLOYMENT_PCT' THEN 'SOCIAL'
    WHEN 'YOUTH_NEET_PCT' THEN 'SOCIAL'
    WHEN 'YOUTH_UNEMPLOYMENT_PCT' THEN 'SOCIAL'
      ELSE 'OTROS'
    END AS sector
  FROM combined
)
SELECT
  classified.*,
  lag(value) OVER series                AS previous_value,
  value - lag(value) OVER series        AS change_absolute,
  round(
    (value - lag(value) OVER series) / NULLIF(abs(lag(value) OVER series), 0) * 100,
    4
  )                                     AS change_percent
FROM classified
WINDOW series AS (PARTITION BY indicator_code ORDER BY period);
`;
