/**
 * La lista de temas de la 0066, ensanchada.
 *
 * Una copia, nunca editada: un cambio posterior a la lista es una migracion
 * posterior con su propia copia. Ver la 0066 para las reglas que esta lista
 * hereda — cada entrada es una raiz y no una palabra, los acentos se quitan
 * antes de comparar, y `\m` ancla al inicio de palabra para que `oro` no
 * entre en *ahorro*.
 */

export const watchlist = `
    ('DIESEL', 'Diesel', 'HIDROCARBUROS', ARRAY['\\mdiesel']),
    ('GASOLINA', 'Gasolina', 'HIDROCARBUROS', ARRAY['\\mgasolin']),
    ('GLP', 'Gas licuado y garrafas', 'HIDROCARBUROS', ARRAY['\\mglp\\M', '\\mgarrafa', '\\mbutano']),
    ('GAS_NATURAL', 'Gas natural', 'HIDROCARBUROS', ARRAY['\\mgas natural', '\\mgasoducto', '\\mgnv\\M']),
    ('YPFB', 'YPFB', 'HIDROCARBUROS', ARRAY['\\mypfb\\M']),
    ('ANH', 'Agencia de hidrocarburos', 'HIDROCARBUROS', ARRAY['\\manh\\M']),
    ('SUBVENCION', 'Subvencion', 'HIDROCARBUROS', ARRAY['\\msubvencion', '\\msubsidio']),
    ('SURTIDOR', 'Surtidores y filas', 'HIDROCARBUROS', ARRAY['\\msurtidor', '\\mestacion de servicio']),
    ('REFINERIA', 'Refinerias', 'HIDROCARBUROS', ARRAY['\\mrefineri', '\\mplanta de gas']),
    ('EXPLORACION', 'Exploracion petrolera', 'HIDROCARBUROS', ARRAY['\\mexplorac', '\\mpozo', '\\mtaladro', '\\mreservorio']),
    ('COMBUSTIBLE', 'Combustibles', 'HIDROCARBUROS', ARRAY['\\mcombustible', '\\mpetroleo', '\\mcrudo', '\\mcarburante', '\\mhidrocarburo']),
    ('ELECTRICIDAD', 'Electricidad', 'ENERGIA', ARRAY['\\melectric', '\\mende\\M', '\\mapagon', '\\mtarifa electrica']),
    ('RENOVABLES', 'Energias renovables', 'ENERGIA', ARRAY['\\msolar', '\\meolic', '\\mfotovoltaic', '\\mbiodiesel', '\\metanol']),
    ('LITIO', 'Litio', 'ENERGIA', ARRAY['\\mlitio', '\\mylb\\M', '\\msalar de uyuni', '\\mcarbonato de litio']),
    ('ENERGIA_ELECTRICA', 'Generacion electrica', 'ENERGIA', ARRAY['\\mhidroelectric', '\\mtermoelectric', '\\mgeneracion electrica', '\\mmegavatio']),
    ('DOLAR', 'Dolar', 'CAMBIARIO', ARRAY['\\mdolar', '\\mdolares']),
    ('TIPO_CAMBIO', 'Tipo de cambio', 'CAMBIARIO', ARRAY['\\mtipo de cambio', '\\mbrecha cambiaria', '\\mdevaluac']),
    ('DIVISAS', 'Divisas', 'CAMBIARIO', ARRAY['\\mdivisa']),
    ('PARALELO', 'Mercado paralelo', 'CAMBIARIO', ARRAY['\\mparalelo', '\\mcambista', '\\mcasa de cambio']),
    ('CRIPTO', 'Criptomonedas', 'CAMBIARIO', ARRAY['\\mcripto', '\\musdt\\M', '\\mstablecoin', '\\mbitcoin']),
    ('REMESAS', 'Remesas', 'CAMBIARIO', ARRAY['\\mremesa']),
    ('RESERVAS', 'Reservas internacionales', 'MONETARIO', ARRAY['\\mreservas internacionales', '\\mrin\\M', '\\mreservas del bcb', '\\mreservas']),
    ('BCB', 'Banco Central', 'MONETARIO', ARRAY['\\mbanco central', '\\mbcb\\M']),
    ('CREDITO', 'Credito y banca', 'MONETARIO', ARRAY['\\mcredito', '\\mbanca', '\\mprestamo', '\\mcartera', '\\mbanco', '\\mbancari', '\\mfassil', '\\mprestatari', '\\mfinanc', '\\mentidad financiera', '\\mecofuturo', '\\mbmsc\\M', '\\mquiebra']),
    ('ASFI', 'Supervision financiera', 'MONETARIO', ARRAY['\\masfi\\M', '\\masoban\\M']),
    ('DEPOSITOS', 'Depositos y ahorro', 'MONETARIO', ARRAY['\\mdeposito', '\\mahorrista', '\\mdpf\\M', '\\mahorro']),
    ('TASAS', 'Tasas de interes', 'MONETARIO', ARRAY['\\mtasa de interes', '\\mtasas de interes', '\\mencaje']),
    ('MICROFINANZAS', 'Microfinanzas', 'MONETARIO', ARRAY['\\mmicrofinan', '\\mmicrocredito', '\\mifd\\M', '\\mcooperativa de ahorro']),
    ('BOLSA', 'Bolsa de valores', 'MONETARIO', ARRAY['\\mbolsa boliviana', '\\mbbv\\M', '\\mtitulariz', '\\memision de bonos']),
    ('SEGUROS', 'Seguros', 'MONETARIO', ARRAY['\\mseguro', '\\maseguradora', '\\msoat\\M']),
    ('PAGOS_DIGITALES', 'Pagos digitales', 'MONETARIO', ARRAY['\\mqr\\M', '\\mbilletera movil', '\\mpago digital', '\\mfintech']),
    ('LIQUIDEZ', 'Liquidez y mora', 'MONETARIO', ARRAY['\\mliquidez', '\\mmora\\M', '\\mrefinanciac', '\\mdiferimiento']),
    ('DINERO', 'Dinero y medios de pago', 'MONETARIO', ARRAY['\\mdinero', '\\mbillete', '\\mefectivo', '\\mmoneda']),
    ('INFLACION', 'Inflacion', 'PRECIOS', ARRAY['\\minflacion', '\\mipc\\M', '\\mindice de precios']),
    ('CANASTA', 'Canasta y carestia', 'PRECIOS', ARRAY['\\mcanasta', '\\mcarestia', '\\mencarec', '\\mcosto de vida']),
    ('ESCASEZ', 'Escasez', 'PRECIOS', ARRAY['\\mescasez', '\\mdesabastec', '\\macaparamiento', '\\mespeculac']),
    ('SOBREPRECIO', 'Sobreprecio y agio', 'PRECIOS', ARRAY['\\msobreprecio', '\\magio\\M', '\\magiotaje']),
    ('ALIMENTOS_BASICOS', 'Alimentos basicos', 'PRECIOS', ARRAY['\\mpan\\M', '\\mharina', '\\mazucar', '\\maceite', '\\marroz', '\\mfideo', '\\malimento', '\\mleche', '\\mlacteo']),
    ('CARNES', 'Carne y pollo', 'PRECIOS', ARRAY['\\mcarne', '\\mpollo', '\\mres\\M', '\\mcerdo']),
    ('HORTALIZAS', 'Verduras y frutas', 'PRECIOS', ARRAY['\\mtomate', '\\mpapa\\M', '\\mcebolla', '\\mverdura', '\\mfruta', '\\mplatano']),
    ('IMPUESTOS', 'Impuestos', 'FISCAL', ARRAY['\\mimpuesto', '\\mtributar', '\\mimpositiv', '\\miva\\M', '\\miue\\M']),
    ('DEUDA', 'Deuda publica', 'FISCAL', ARRAY['\\mdeuda', '\\mbono soberano', '\\mendeud']),
    ('DEFICIT', 'Deficit y presupuesto', 'FISCAL', ARRAY['\\mdeficit', '\\mpresupuest', '\\mpge\\M', '\\mtesoro general', '\\mtgn\\M']),
    ('GASTO_PUBLICO', 'Gasto publico', 'FISCAL', ARRAY['\\mgasto publico', '\\mausteridad', '\\mgasto corriente']),
    ('RECAUDACION', 'Recaudacion', 'FISCAL', ARRAY['\\mrecaudac', '\\mimpuestos nacionales', '\\mfactura', '\\mnit\\M']),
    ('REGALIAS', 'Regalias', 'FISCAL', ARRAY['\\mregalia', '\\mcoparticipac', '\\mide\\M']),
    ('CONTRATACIONES', 'Contrataciones del Estado', 'FISCAL', ARRAY['\\mlicitac', '\\madjudic', '\\mcontrato estatal', '\\mfideicomiso', '\\mcontrato']),
    ('PAGOS', 'Pagos y cobros', 'FISCAL', ARRAY['\\mingreso', '\\mpago de', '\\mpagar', '\\mcobrar', '\\mdeuda salarial', '\\mtarifa', '\\mcobro']),
    ('CONTRABANDO', 'Contrabando', 'COMERCIO_EXTERIOR', ARRAY['\\mcontrabando', '\\mchuto', '\\milicit']),
    ('EXPORTACION', 'Exportaciones', 'COMERCIO_EXTERIOR', ARRAY['\\mexport']),
    ('IMPORTACION', 'Importaciones', 'COMERCIO_EXTERIOR', ARRAY['\\mimport', '\\marancel']),
    ('ADUANA', 'Aduana y frontera', 'COMERCIO_EXTERIOR', ARRAY['\\maduana', '\\mfrontera', '\\mzona franca', '\\mpaso fronterizo']),
    ('BALANZA', 'Balanza comercial', 'COMERCIO_EXTERIOR', ARRAY['\\mbalanza comercial', '\\msaldo comercial', '\\mterminos de intercambio']),
    ('ACUERDOS', 'Acuerdos comerciales', 'COMERCIO_EXTERIOR', ARRAY['\\mmercosur', '\\macuerdo comercial', '\\mlibre comercio', '\\mcan\\M', '\\mbrics\\M']),
    ('PUERTOS', 'Puertos y transito', 'COMERCIO_EXTERIOR', ARRAY['\\mpuerto', '\\marica\\M', '\\miquique\\M', '\\mhidrovia', '\\mbioceanic']),
    ('SOCIOS_COMERCIALES', 'Paises y socios comerciales', 'COMERCIO_EXTERIOR', ARRAY['\\margentina', '\\mbrasil', '\\mchile', '\\mperu\\M', '\\mparaguay', '\\mchina', '\\mestados unidos', '\\meeuu\\M', '\\muruguay', '\\munion europea', '\\mrusia', '\\mamerica latina']),
    ('FERIA', 'Ferias y mercados populares', 'COMERCIO_INTERNO', ARRAY['\\mferia', '\\mferiant', '\\m16 de julio\\M', '\\mfeicobol', '\\mexpo\\M', '\\mexposicion']),
    ('MERCADO_ABASTO', 'Mercados de abasto', 'COMERCIO_INTERNO', ARRAY['\\mmercado de abasto', '\\mmercado central', '\\mvivander', '\\mpuesto de venta', '\\mabasto', '\\mmercado popular']),
    ('COMERCIO_MINORISTA', 'Comercio minorista', 'COMERCIO_INTERNO', ARRAY['\\mminorista', '\\mcomerciante', '\\mtienda de barrio', '\\mambulante']),
    ('SUPERMERCADO', 'Supermercados y cadenas', 'COMERCIO_INTERNO', ARRAY['\\msupermercado', '\\mhipermercado', '\\mcentro comercial', '\\mmayorista']),
    ('ECOMMERCE', 'Comercio electronico', 'COMERCIO_INTERNO', ARRAY['\\mcomercio electronico', '\\mecommerce', '\\mmarketplace', '\\mdelivery', '\\mtienda en linea']),
    ('INFORMALIDAD', 'Informalidad', 'COMERCIO_INTERNO', ARRAY['\\minformalidad', '\\meconomia informal', '\\mcuenta propia', '\\mcuentapropi']),
    ('EMPRENDIMIENTO', 'Emprendimiento y pymes', 'COMERCIO_INTERNO', ARRAY['\\memprend', '\\mpyme', '\\mmicroempresa', '\\munipersonal']),
    ('FRANQUICIAS', 'Marcas y franquicias', 'COMERCIO_INTERNO', ARRAY['\\mfranquicia', '\\mcadena de tiendas', '\\mretail']),
    ('CONSUMO', 'Consumo, compra y venta', 'COMERCIO_INTERNO', ARRAY['\\mconsumo', '\\mconsumidor', '\\mcompra', '\\mventa', '\\mdemanda interna', '\\mcanasta familiar']),
    ('SOYA', 'Soya y oleaginosas', 'SECTOR_REAL', ARRAY['\\msoya', '\\moleagin', '\\mgirasol', '\\msesamo']),
    ('GANADERIA', 'Ganaderia', 'SECTOR_REAL', ARRAY['\\mganader', '\\mcabeza de ganado', '\\mfaeneo', '\\mlecher', '\\mleche']),
    ('AVICULTURA', 'Avicultura', 'SECTOR_REAL', ARRAY['\\mavicult', '\\mgranja avicola', '\\mhuevo']),
    ('MINERIA', 'Mineria', 'SECTOR_REAL', ARRAY['\\mmineri', '\\mminero', '\\mcomibol\\M', '\\mcooperativa minera', '\\mminer', '\\mhuanuni', '\\mcolquiri', '\\mcooperativista']),
    ('ORO', 'Oro y metales', 'SECTOR_REAL', ARRAY['\\moro\\M', '\\mplata\\M', '\\mzinc', '\\mestano', '\\mplomo', '\\mwolfram']),
    ('AGRO', 'Agricultura', 'SECTOR_REAL', ARRAY['\\mmaiz', '\\msorgo', '\\mtrigo', '\\mhectarea', '\\msiembra', '\\mcosecha', '\\magro', '\\mtransgenic', '\\manapo\\M', '\\mproductor', '\\mcultivo', '\\msenasag\\M', '\\msuelo', '\\mriego', '\\msemilla']),
    ('QUINUA', 'Quinua y granos andinos', 'SECTOR_REAL', ARRAY['\\mquinua', '\\mcanahua', '\\mamaranto', '\\mtarwi']),
    ('CAFE_CACAO', 'Cafe, cacao y castana', 'SECTOR_REAL', ARRAY['\\mcafe\\M', '\\mcacao', '\\mcastana', '\\mamazonic']),
    ('AZUCAR_CANA', 'Cana y azucar', 'SECTOR_REAL', ARRAY['\\mcana de azucar', '\\mingenio azucarero', '\\mzafra']),
    ('COCA', 'Coca', 'SECTOR_REAL', ARRAY['\\mcoca\\M', '\\mcocal', '\\madepcoca\\M']),
    ('MADERA', 'Madera y forestal', 'SECTOR_REAL', ARRAY['\\mmadera', '\\mforestal', '\\maserradero']),
    ('TEXTIL', 'Textiles y confeccion', 'SECTOR_REAL', ARRAY['\\mtextil', '\\mconfeccion', '\\mcalzado', '\\mcuero']),
    ('MANUFACTURA', 'Manufactura', 'SECTOR_REAL', ARRAY['\\mmanufactur', '\\mindustria', '\\mfabrica', '\\mcni\\M', '\\mplanta de', '\\murea', '\\mmutun', '\\msiderurg', '\\mensambladora', '\\menvase']),
    ('CEMENTO', 'Cemento y materiales', 'SECTOR_REAL', ARRAY['\\mcemento', '\\mladrillo', '\\mfierro', '\\msoboce\\M']),
    ('BEBIDAS', 'Bebidas y cerveceria', 'SECTOR_REAL', ARRAY['\\mcerveceri', '\\mcerveza', '\\mgaseosa', '\\membotellad']),
    ('PESCA', 'Pesca y acuicultura', 'SECTOR_REAL', ARRAY['\\mpesca', '\\mpiscicultura', '\\macuicultura']),
    ('PRODUCCION', 'Produccion y productos', 'SECTOR_REAL', ARRAY['\\mproducc', '\\mproducto', '\\mproductiv', '\\mfabricacion', '\\mplanta industrial']),
    ('EMPLEO', 'Empleo', 'LABORAL', ARRAY['\\mempleo', '\\mdesempleo', '\\mempleab', '\\mfuente laboral', '\\mtrabajador', '\\mlaboral', '\\mchofer']),
    ('SALARIO', 'Salarios', 'LABORAL', ARRAY['\\msalari', '\\maguinaldo', '\\mhaberes', '\\msueldo']),
    ('SINDICATOS', 'Sindicatos', 'LABORAL', ARRAY['\\msindicat', '\\mcob\\M', '\\mcentral obrera', '\\mfederacion de trabajadores']),
    ('JUBILACION', 'Jubilacion y pensiones', 'LABORAL', ARRAY['\\mjubilac', '\\mpension', '\\mgestora publica', '\\maportes', '\\mgestora']),
    ('TRABAJO_INFANTIL', 'Trabajo infantil y precario', 'LABORAL', ARRAY['\\mtrabajo infantil', '\\mtrabajo precario', '\\mexplotacion laboral']),
    ('MIGRACION', 'Migracion laboral', 'LABORAL', ARRAY['\\mmigrante', '\\mmigracion', '\\memigrac', '\\mdiaspora']),
    ('TRANSPORTE_PESADO', 'Transporte pesado', 'TRANSPORTE', ARRAY['\\mtransporte pesado', '\\mcamion', '\\mcisterna', '\\mflota']),
    ('TRANSPORTE_PUBLICO', 'Transporte publico', 'TRANSPORTE', ARRAY['\\mtransporte publico', '\\mminibus', '\\mpasaje', '\\mtrufi', '\\mtelferico', '\\mtransporte', '\\mvehiculo', '\\mteleferico', '\\mbus\\M', '\\mbuses\\M', '\\mterminal de buses', '\\mpasajero']),
    ('AEROLINEAS', 'Aerolineas', 'TRANSPORTE', ARRAY['\\maerolinea', '\\mboa\\M', '\\maeropuerto', '\\mvuelo', '\\maasana\\M', '\\mdgac\\M', '\\maeronautic', '\\mavion', '\\mamaszonas', '\\mlamia\\M']),
    ('FERROCARRIL', 'Ferrocarril', 'TRANSPORTE', ARRAY['\\mferrocarril', '\\mtren\\M', '\\mferroviari']),
    ('CARRETERAS', 'Carreteras', 'INFRAESTRUCTURA', ARRAY['\\mcarretera', '\\mdoble via', '\\mpuente', '\\mruta\\M', '\\mcamino', '\\mtramo', '\\mvia publica', '\\mvias\\M', '\\mdesvio', '\\mabc\\M']),
    ('OBRAS', 'Obras publicas', 'INFRAESTRUCTURA', ARRAY['\\mobra publica', '\\mconstruccion', '\\mcadeco\\M', '\\minfraestructura', '\\mproyecto', '\\mobras', '\\msillar', '\\mconstructor', '\\medificio', '\\mterminal']),
    ('AGUA', 'Agua y saneamiento', 'SERVICIOS_BASICOS', ARRAY['\\magua potable', '\\malcantarillado', '\\mepsas\\M', '\\msaneamiento']),
    ('BASURA', 'Residuos', 'SERVICIOS_BASICOS', ARRAY['\\mbasura', '\\mresiduo', '\\mrelleno sanitario']),
    ('INTERNET', 'Internet y telecomunicaciones', 'TECNOLOGIA', ARRAY['\\minternet', '\\mtelecomunicac', '\\mentel\\M', '\\mtigo\\M', '\\mfibra optica', '\\mtecnolog', '\\mhuawei', '\\mdigital', '\\maplicacion movil', '\\mcelular', '\\msmartphone', '\\msamsung', '\\mopenai', '\\msoftware']),
    ('DIGITALIZACION', 'Digitalizacion', 'TECNOLOGIA', ARRAY['\\mdigitalizac', '\\minteligencia artificial', '\\mciberseguridad', '\\mdatos abiertos']),
    ('VIVIENDA', 'Vivienda', 'VIVIENDA', ARRAY['\\mvivienda', '\\malquiler', '\\minmobiliari', '\\mloteamiento']),
    ('TURISMO', 'Turismo', 'TURISMO', ARRAY['\\mturis', '\\mhoteler', '\\mvisitante extranjero']),
    ('GASTRONOMIA', 'Gastronomia', 'TURISMO', ARRAY['\\mgastronom', '\\mrestaurante', '\\mchef\\M']),
    ('SALUD', 'Salud', 'SALUD', ARRAY['\\msalud', '\\mhospital', '\\mmedicament', '\\msus\\M', '\\mepidemi', '\\mcovid', '\\mpandemia', '\\mcoronavirus', '\\mcuarentena', '\\mvacuna', '\\mfarmacia', '\\mbioseguridad', '\\menfermedad']),
    ('EDUCACION', 'Educacion', 'EDUCACION', ARRAY['\\meducac', '\\mescuela', '\\muniversidad', '\\mmaestro', '\\mestudiante']),
    ('BLOQUEO', 'Bloqueos', 'CONFLICTO', ARRAY['\\mbloqueo']),
    ('PARO', 'Paros y protestas', 'CONFLICTO', ARRAY['\\mparo\\M', '\\mprotesta', '\\mmovilizac', '\\mmarcha\\M', '\\mhuelga']),
    ('GREMIALES', 'Gremiales', 'CONFLICTO', ARRAY['\\mgremial', '\\mtransportista']),
    ('AVASALLAMIENTO', 'Avasallamientos y tierras', 'CONFLICTO', ARRAY['\\mavasallam', '\\mtierra fiscal', '\\minterculturales', '\\mtierra', '\\minra\\M']),
    ('ELECCIONES', 'Elecciones', 'INSTITUCIONAL', ARRAY['\\melecc', '\\mvoto\\M', '\\mpadron electoral', '\\mtse\\M']),
    ('CORRUPCION', 'Corrupcion', 'INSTITUCIONAL', ARRAY['\\mcorrupc', '\\mcoima', '\\mmalversac', '\\mdesfalco', '\\mcontraloria']),
    ('JUSTICIA', 'Justicia', 'INSTITUCIONAL', ARRAY['\\mfiscalia', '\\mtribunal', '\\mjuez\\M', '\\mimputac', '\\msentencia']),
    ('GOBIERNO', 'Gobierno y ministerios', 'INSTITUCIONAL', ARRAY['\\mministerio', '\\mgobierno nacional', '\\mdecreto supremo', '\\mgabinete', '\\mgobierno', '\\mministr', '\\mviceministr', '\\mdecreto', '\\mestado de excepcion', '\\mpoder ejecutivo', '\\mpalacio quemado', '\\mpresidente arce', '\\mluis arce', '\\mrodrigo paz', '\\mevo morales', '\\mjeanine anez', '\\mmontenegro', '\\mestado de sitio']),
    ('AUTONOMIAS', 'Gobernaciones y alcaldias', 'INSTITUCIONAL', ARRAY['\\mgobernac', '\\malcaldia', '\\mmunicipi', '\\mautonom']),
    ('DIALOGO', 'Dialogo y acuerdos', 'INSTITUCIONAL', ARRAY['\\mdialogo', '\\macuerdo', '\\mnegociacion', '\\mmesa tecnica', '\\mconsenso', '\\mpacto', '\\mcumbre', '\\mconvenio']),
    ('ASAMBLEA', 'Asamblea Legislativa', 'INSTITUCIONAL', ARRAY['\\masamblea legislativa', '\\mdiputad', '\\msenador', '\\mley\\M', '\\mproyecto de ley', '\\mcamara de diputados', '\\mcamara de senadores', '\\mnormativa']),
    ('SEGURIDAD', 'Seguridad ciudadana', 'SEGURIDAD', ARRAY['\\mdelincuen', '\\mrobo\\M', '\\matraco', '\\mextorsion', '\\minseguridad', '\\mpolicia', '\\mmilitar', '\\mfuerzas armadas']),
    ('NARCOTRAFICO', 'Narcotrafico', 'SEGURIDAD', ARRAY['\\mnarcotrafic', '\\mdroga', '\\mfelcn\\M', '\\mcocaina']),
    ('LAVADO', 'Lavado de dinero', 'SEGURIDAD', ARRAY['\\mlavado de dinero', '\\mlegitimacion de ganancias', '\\muif\\M']),
    ('SEQUIA', 'Sequia y heladas', 'AMBIENTE', ARRAY['\\msequia', '\\mhelada', '\\mgranizada', '\\mdeficit hidrico']),
    ('INCENDIOS', 'Incendios forestales', 'AMBIENTE', ARRAY['\\mincendio forestal', '\\mchaqueo', '\\mquema\\M', '\\mfoco de calor', '\\mincendio']),
    ('INUNDACION', 'Inundaciones', 'AMBIENTE', ARRAY['\\minundac', '\\mriada', '\\mdesborde', '\\mmazamorra']),
    ('DEFORESTACION', 'Deforestacion', 'AMBIENTE', ARRAY['\\mdeforestac', '\\mtala\\M', '\\mareas protegidas']),
    ('CAMBIO_CLIMATICO', 'Cambio climatico', 'AMBIENTE', ARRAY['\\mcambio climatico', '\\mcalentamiento global', '\\mtransicion energetica']),
    ('EMERGENCIA', 'Emergencias y desastres', 'AMBIENTE', ARRAY['\\memergencia', '\\mdesastre', '\\mdamnificad', '\\malerta roja', '\\malerta naranja', '\\mlluvia', '\\maccidente']),
    ('POBREZA', 'Pobreza y desigualdad', 'SOCIAL', ARRAY['\\mpobreza', '\\mdesigualdad', '\\mextrema pobreza', '\\mgini\\M']),
    ('BONOS_SOCIALES', 'Bonos sociales', 'SOCIAL', ARRAY['\\mbono juancito', '\\mrenta dignidad', '\\mbono juana azurduy', '\\mtransferencia condicionada', '\\mbono', '\\mcontra el hambre', '\\mpepe', '\\msubsidio de lactancia']),
    ('GENERO', 'Genero', 'SOCIAL', ARRAY['\\mfeminicid', '\\mviolencia contra la mujer', '\\mbrecha de genero', '\\mequidad de genero']),
    ('NINEZ', 'Ninez y adolescencia', 'SOCIAL', ARRAY['\\mninez', '\\madolescen', '\\mdefensoria de la ninez']),
    ('PUEBLOS_INDIGENAS', 'Pueblos indigenas', 'SOCIAL', ARRAY['\\mindigena', '\\mtco\\M', '\\mconsulta previa', '\\moriginari']),
    ('DEMOGRAFIA', 'Poblacion y censo', 'SOCIAL', ARRAY['\\mcenso', '\\mpoblacion', '\\mine\\M', '\\mproyeccion demografica']),
    ('GRUPOS_SOCIALES', 'Mujeres, jovenes y familias', 'SOCIAL', ARRAY['\\mmujer', '\\mjoven', '\\mnino', '\\mfamilia', '\\madulto mayor', '\\mfundacion']),
    ('INVERSION', 'Inversion', 'ACTIVIDAD', ARRAY['\\minversion', '\\minversor', '\\minversionista']),
    ('PIB', 'Crecimiento y PIB', 'ACTIVIDAD', ARRAY['\\mpib\\M', '\\mcrecimiento economico', '\\mproducto interno bruto', '\\mrecesion', '\\mcrecimiento', '\\mcrecio', '\\mactividad economica']),
    ('ORGANISMOS', 'Organismos internacionales', 'ACTIVIDAD', ARRAY['\\mfmi\\M', '\\mbanco mundial', '\\mcaf\\M', '\\mbid\\M', '\\mcepal\\M']),
    ('CALIFICADORAS', 'Calificadoras de riesgo', 'ACTIVIDAD', ARRAY['\\mcalificadora', '\\mmoodys', '\\mfitch', '\\mstandard and poors', '\\mriesgo pais']),
    ('COMPETITIVIDAD', 'Competitividad', 'ACTIVIDAD', ARRAY['\\mcompetitividad', '\\mproductividad', '\\mclima de negocios', '\\mdesarrollo economico', '\\mreactivacion', '\\mreactivar', '\\minnovacion']),
    ('EMPRESAS', 'Empresas y empresarios', 'ACTIVIDAD', ARRAY['\\mempresa', '\\mempresari', '\\msector privado', '\\mcamara de industria', '\\mcamara de comercio', '\\mcainco\\M', '\\mcepb\\M', '\\mgerente', '\\mfirma privada', '\\mrueda de negocios', '\\mexpocruz', '\\mdirectorio', '\\mcorporativ', '\\mmarca comercial', '\\mcliente']),
    ('ECONOMIA_GENERAL', 'Economia, en general', 'ACTIVIDAD', ARRAY['\\meconomia', '\\meconomic', '\\meconomist']),
    ('CRISIS', 'Crisis economica', 'ACTIVIDAD', ARRAY['\\mcrisis', '\\mrecesion', '\\mdesaceleracion', '\\msituacion economica', '\\mmodelo economico']),
    ('INDICADORES', 'Informes y proyecciones', 'ACTIVIDAD', ARRAY['\\minforme', '\\mproyeccion', '\\mestudio', '\\mencuesta', '\\mestadistica', '\\manalista', '\\mexperto', '\\mpronostico', '\\mranking', '\\mindicador']),
    ('ESTATALES', 'Empresas estatales', 'ACTIVIDAD', ARRAY['\\mempresa estatal', '\\mempresas publicas', '\\memapa\\M', '\\mboa\\M', '\\mentel\\M', '\\mcomibol\\M', '\\myacimientos', '\\msedem\\M', '\\mbocom'])
`;
