import type { ExogenousGroup, ExogenousSpec } from './exogenous-spec';

/**
 * Las cotizaciones de los vecinos y de los lácteos, en dólares por tonelada,
 * republicadas por FAO/GIEWS: el trigo y el maíz argentinos (de donde viene la
 * harina que Bolivia importa), la carne brasileña (con la que compite la
 * exportación cruceña) y los lácteos que fijan el precio de la leche en polvo.
 */

const neighbour = (
  code: string,
  uuid: string,
  group: ExogenousGroup,
  product: string,
  productLabel: string,
  name: string,
  market: string,
  note: string,
): ExogenousSpec => ({
  code: `EXO_${code}`,
  group,
  product,
  productLabel,
  name,
  scope: market === 'Argentina' || market === 'Brasil' ? 'REGIONAL' : 'WORLD',
  market,
  unit: 'US$/tonelada',
  kind: 'PRICE',
  note,
  origin: { kind: 'FAO', uuid },
});

const DAIRY = 'Promedio de los precios indicativos de exportación de Europa y Oceanía.';

export const FAO_INTERNATIONAL: readonly ExogenousSpec[] = [
  neighbour(
    'WHEAT_ARGENTINA',
    'e23b83a7-7cf7-40b0-87f7-6c03a2d3b2bc',
    'AGRICULTURE',
    'WHEAT',
    'Trigo',
    'Trigo, Argentina (Up River)',
    'Argentina',
    'El trigo con que se muele buena parte de la harina que Bolivia importa.',
  ),
  neighbour(
    'MAIZE_ARGENTINA',
    '3fefffb8-a60a-43f6-9f70-b71479f44a04',
    'AGRICULTURE',
    'MAIZE',
    'Maíz',
    'Maíz, Argentina (Up River)',
    'Argentina',
    'El maíz del vecino que abastece a la avicultura cuando falta el nacional.',
  ),
  neighbour(
    'MAIZE_BRAZIL',
    'd471f6ae-21d2-4c05-a910-55f042fdebf1',
    'AGRICULTURE',
    'MAIZE',
    'Maíz',
    'Maíz forrajero, Brasil (Paranaguá)',
    'Brasil',
    'Maíz forrajero en el puerto brasileño.',
  ),
  neighbour(
    'SORGHUM',
    '16bc8be4-6b15-4551-a9d8-7084ddee3a1c',
    'AGRICULTURE',
    'SORGHUM',
    'Sorgo',
    'Sorgo, EE. UU. (Golfo)',
    'EE. UU. (Golfo)',
    'Sustituto del maíz en los alimentos balanceados; el Banco Mundial dejó de publicarlo en 2020.',
  ),
  neighbour(
    'BEEF_BRAZIL',
    '897688ad-9181-4c54-a7fd-abd48684797a',
    'LIVESTOCK',
    'BEEF',
    'Carne de res',
    'Carne bovina, exportación de Brasil',
    'Brasil',
    'El competidor directo de la carne cruceña en el mercado chino.',
  ),
  neighbour(
    'POULTRY_BRAZIL',
    'ab4ef0f6-aa61-4fd2-ad26-29f6b82a8311',
    'LIVESTOCK',
    'CHICKEN',
    'Carne de pollo',
    'Pollo, exportación de Brasil',
    'Brasil',
    'El mayor exportador de pollo del mundo, en la frontera.',
  ),
  neighbour(
    'PORK_BRAZIL',
    '223de48c-f284-486a-8bb6-fdbdaf81a4ba',
    'LIVESTOCK',
    'PORK',
    'Carne de cerdo',
    'Cerdo, exportación de Brasil',
    'Brasil',
    'Porcino, la otra carne de la región.',
  ),
  neighbour(
    'WHOLE_MILK_POWDER',
    '70d0099b-3cda-4997-9bf1-dfc86ed1927c',
    'LIVESTOCK',
    'DAIRY',
    'Lácteos',
    'Leche entera en polvo',
    'Europa y Oceanía',
    DAIRY,
  ),
  neighbour(
    'SKIM_MILK_POWDER',
    '050a093f-268a-415b-8e1a-a87033d1908f',
    'LIVESTOCK',
    'DAIRY',
    'Lácteos',
    'Leche descremada en polvo',
    'Europa y Oceanía',
    DAIRY,
  ),
  neighbour(
    'CHEDDAR',
    '23397429-69b2-472f-bfed-19d0bd943937',
    'LIVESTOCK',
    'CHEESE',
    'Queso',
    'Queso cheddar',
    'Europa y Oceanía',
    DAIRY,
  ),
  neighbour(
    'BUTTER',
    'a2d52862-666a-45d6-8887-2f6a56205000',
    'LIVESTOCK',
    'DAIRY',
    'Lácteos',
    'Mantequilla',
    'Europa y Oceanía',
    DAIRY,
  ),
];
