/**
 * The words this corpus uses, and how they are spelled.
 *
 * Kept apart from the speller because these two are different kinds of thing:
 * the rules next door say what Spanish does to any word with a given ending,
 * while this is a record of what these outlets actually write about. It grows
 * whenever a headline reads wrong, and it grows by one line at a time.
 */

/** Words this corpus uses whose accented spelling is not in doubt. */
export const SPELLING: Record<string, string> = {
  // Economy and money
  dolar: 'dólar',
  dolares: 'dólares',
  economia: 'economía',
  economico: 'económico',
  economica: 'económica',
  economicos: 'económicos',
  economicas: 'económicas',
  credito: 'crédito',
  creditos: 'créditos',
  deficit: 'déficit',
  superavit: 'superávit',
  interes: 'interés',
  intereses: 'intereses',
  inflacion: 'inflación',
  recesion: 'recesión',
  devaluacion: 'devaluación',
  exportacion: 'exportación',
  exportaciones: 'exportaciones',
  importacion: 'importación',
  importaciones: 'importaciones',
  produccion: 'producción',
  inversion: 'inversión',
  inversiones: 'inversiones',
  recaudacion: 'recaudación',
  subvencion: 'subvención',
  cotizacion: 'cotización',
  licitacion: 'licitación',
  liquidacion: 'liquidación',
  facturacion: 'facturación',
  presion: 'presión',
  gestion: 'gestión',
  transaccion: 'transacción',
  millon: 'millón',
  billon: 'billón',
  diesel: 'diésel',
  gasolina: 'gasolina',
  petroleo: 'petróleo',
  energetico: 'energético',
  energetica: 'energética',
  electrico: 'eléctrico',
  electrica: 'eléctrica',
  electricos: 'eléctricos',
  electricas: 'eléctricas',
  hectareas: 'hectáreas',
  hectarea: 'hectárea',
  quintal: 'quintal',
  logistica: 'logística',
  estadistica: 'estadística',
  estadisticas: 'estadísticas',

  // Institutions and government
  gobierno: 'gobierno',
  publica: 'pública',
  publicas: 'públicas',
  publicos: 'públicos',
  politica: 'política',
  politico: 'político',
  politicas: 'políticas',
  politicos: 'políticos',
  camara: 'cámara',
  camaras: 'cámaras',
  comision: 'comisión',
  asociacion: 'asociación',
  federacion: 'federación',
  confederacion: 'confederación',
  administracion: 'administración',
  regulacion: 'regulación',
  fiscalizacion: 'fiscalización',
  procuraduria: 'procuraduría',
  contraloria: 'contraloría',
  ministerio: 'ministerio',
  region: 'región',
  regiones: 'regiones',
  municipio: 'municipio',
  municipios: 'municipios',

  // Conflict and crisis
  crisis: 'crisis',
  paro: 'paro',
  presion_social: 'presión social',
  movilizacion: 'movilización',
  movilizaciones: 'movilizaciones',
  manifestacion: 'manifestación',
  negociacion: 'negociación',
  negociaciones: 'negociaciones',
  reunion: 'reunión',
  sesion: 'sesión',
  decision: 'decisión',
  resolucion: 'resolución',
  aprobacion: 'aprobación',
  abrogacion: 'abrogación',
  derogacion: 'derogación',
  suspension: 'suspensión',
  interpelacion: 'interpelación',
  denuncia: 'denuncia',
  investigacion: 'investigación',
  corrupcion: 'corrupción',
  especulacion: 'especulación',
  escasez: 'escasez',
  atencion: 'atención',
  situacion: 'situación',
  condicion: 'condición',
  condiciones: 'condiciones',

  // Common verbs and adverbs whose accent is unambiguous here
  seran: 'serán',
  estan: 'están',
  esta: 'esta',
  mas: 'más',
  segun: 'según',
  tambien: 'también',
  asi: 'así',
  aun: 'aún',
  todavia: 'todavía',
  despues: 'después',
  ademas: 'además',
  atras: 'atrás',
  detras: 'detrás',
  proximo: 'próximo',
  proxima: 'próxima',
  ultimo: 'último',
  ultima: 'última',
  ultimos: 'últimos',
  ultimas: 'últimas',
  dia: 'día',
  dias: 'días',
  ano: 'año',
  anos: 'años',
  mes: 'mes',
  numero: 'número',
  minimo: 'mínimo',
  maximo: 'máximo',
  rapido: 'rápido',
  practica: 'práctica',
  tecnico: 'técnico',
  tecnica: 'técnica',
  basico: 'básico',
  basica: 'básica',
  critico: 'crítico',
  critica: 'crítica',
  historico: 'histórico',
  historica: 'histórica',
  automatico: 'automático',
  telefonico: 'telefónico',
  cientifico: 'científico',
  quimico: 'químico',
  medico: 'médico',
  medicos: 'médicos',
  jovenes: 'jóvenes',
  arboles: 'árboles',
  facil: 'fácil',
  dificil: 'difícil',
  util: 'útil',
  debil: 'débil',
  movil: 'móvil',
  civil: 'civil',
  transito: 'tránsito',
  credibilidad: 'credibilidad',
};

/** Places and institutions, which also decide their own capitalisation. */
export const NAMES: Record<string, string> = {
  potosi: 'Potosí',
  'santa cruz': 'Santa Cruz',
  'la paz': 'La Paz',
  cochabamba: 'Cochabamba',
  oruro: 'Oruro',
  tarija: 'Tarija',
  chuquisaca: 'Chuquisaca',
  sucre: 'Sucre',
  beni: 'Beni',
  pando: 'Pando',
  'el alto': 'El Alto',
  bolivia: 'Bolivia',
  boliviano: 'boliviano',
  bolivianos: 'bolivianos',
  ypfb: 'YPFB',
  bcb: 'BCB',
  ine: 'INE',
  asfi: 'ASFI',
  anh: 'ANH',
  bbv: 'BBV',
  fmi: 'FMI',
  bid: 'BID',
  caf: 'CAF',
  cainco: 'CAINCO',
  cao: 'CAO',
  anapo: 'ANAPO',
  'cerro rico': 'Cerro Rico',
  mutun: 'Mutún',
  chiquitania: 'Chiquitania',
  chapare: 'Chapare',
  yacuiba: 'Yacuiba',
  montero: 'Montero',
  trinidad: 'Trinidad',
  cobija: 'Cobija',
  china: 'China',
  argentina: 'Argentina',
  brasil: 'Brasil',
  peru: 'Perú',
  chile: 'Chile',
  paraguay: 'Paraguay',
  eeuu: 'EEUU',
  huawei: 'Huawei',
};
