from __future__ import annotations

import ast
import re
from pathlib import Path


def migration_source(migrations: Path) -> str:
    return '\n'.join(path.read_text(encoding='utf-8') for path in sorted(migrations.glob('*.ts')))


def split_definitions(body: str) -> list[str]:
    definitions: list[str] = []
    current: list[str] = []
    depth = 0
    for character in body:
        if character == '(':
            depth += 1
        elif character == ')':
            depth -= 1
        if character == ',' and depth == 0:
            definitions.append(''.join(current).strip())
            current = []
        else:
            current.append(character)
    if current:
        definitions.append(''.join(current).strip())
    return definitions


def normalized_type(definition: str) -> str:
    lowered = definition.lower()
    if lowered.startswith('bigint generated by default as identity'):
        return 'bigint generated by default as identity'
    match = re.match(r'([a-z]+(?:\(\d+(?:,\d+)?\))?)', lowered)
    return match.group(1) if match else ''


def expected_type(raw: str, primary_key: bool) -> str:
    base = raw.removesuffix('?').lower()
    return 'bigint generated by default as identity' if base == 'bigint' and primary_key else base


def parse_tables(sql: str) -> dict[tuple[str, str], dict[str, object]]:
    tables: dict[tuple[str, str], dict[str, object]] = {}
    pattern = re.compile(r'CREATE TABLE\s+(\w+)\.(\w+)\s*\((.*?)\n\);', re.I | re.S)
    for schema, table, body in pattern.findall(sql):
        columns: dict[str, dict[str, object]] = {}
        uniques: set[tuple[str, ...]] = set()
        for definition in split_definitions(body):
            if re.match(r'(?:CONSTRAINT\s+\w+\s+)?UNIQUE\s*\(', definition, re.I):
                match = re.search(r'UNIQUE\s*\(([^)]+)\)', definition, re.I)
                if match:
                    uniques.add(tuple(item.strip() for item in match.group(1).split(',')))
                continue
            if definition.upper().startswith(('CONSTRAINT ', 'PRIMARY KEY', 'CHECK ')):
                continue
            match = re.match(r'(\w+)\s+(.+)', definition, re.S)
            if not match:
                continue
            column, remainder = match.groups()
            columns[column] = {
                'type': normalized_type(remainder.strip()),
                'nullable': not bool(re.search(r'\bNOT NULL\b', remainder, re.I)),
                'primary_key': bool(re.search(r'\bPRIMARY KEY\b', remainder, re.I)),
                'unique': bool(re.search(r'\bUNIQUE\b', remainder, re.I)),
            }
            if columns[column]['unique']:
                uniques.add((column,))
        tables[(schema, table)] = {'columns': columns, 'uniques': uniques}

    alter_pattern = re.compile(
        r'ALTER TABLE\s+(\w+)\.(\w+)\s+ADD COLUMN(?: IF NOT EXISTS)?\s+(\w+)\s+([^,;]+)',
        re.I,
    )
    for schema, table, column, remainder in alter_pattern.findall(sql):
        key = (schema, table)
        if key not in tables or column in tables[key]['columns']:
            continue
        tables[key]['columns'][column] = {
            'type': normalized_type(remainder.strip()),
            'nullable': not bool(re.search(r'\bNOT NULL\b', remainder, re.I)),
            'primary_key': bool(re.search(r'\bPRIMARY KEY\b', remainder, re.I)),
            'unique': bool(re.search(r'\bUNIQUE\b', remainder, re.I)),
        }

    set_not_null_pattern = re.compile(
        r'ALTER TABLE\s+(\w+)\.(\w+)\s+ALTER COLUMN\s+(\w+)\s+SET NOT NULL',
        re.I,
    )
    for schema, table, column in set_not_null_pattern.findall(sql):
        key = (schema, table)
        if key in tables and column in tables[key]['columns']:
            tables[key]['columns'][column]['nullable'] = False
    return tables


def load_fk_targets(generator: Path) -> dict[str, tuple[str, str, str]]:
    tree = ast.parse(generator.read_text(encoding='utf-8'))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == 'FK_TARGETS' for target in node.targets
        ):
            return ast.literal_eval(node.value)
    raise RuntimeError('FK_TARGETS was not found')


def parse_fks(sql: str) -> dict[str, tuple[str, str, str]]:
    pattern = re.compile(
        r'ALTER TABLE\s+(\w+)\.(\w+)\s+ADD CONSTRAINT\s+\w+\s+'
        r'FOREIGN KEY\s*\((\w+)\)\s+REFERENCES\s+(\w+)\.(\w+)\s*\((\w+)\)', re.I,
    )
    return {
        f'{schema}.{table}.{column}': (target_schema, target_table, target_column)
        for schema, table, column, target_schema, target_table, target_column in pattern.findall(sql)
    }


def leading_index_columns(sql: str, tables: dict[tuple[str, str], dict[str, object]]) -> set[str]:
    covered: set[str] = set()
    for (schema, table), definition in tables.items():
        for unique in definition['uniques']:
            if unique:
                covered.add(f'{schema}.{table}.{unique[0]}')
        for column, properties in definition['columns'].items():
            if properties['primary_key']:
                covered.add(f'{schema}.{table}.{column}')
    pattern = re.compile(
        r'CREATE\s+(?:UNIQUE\s+)?INDEX\s+\w+\s+ON\s+(\w+)\.(\w+)\s*\(([^)]+)\)', re.I,
    )
    for schema, table, columns in pattern.findall(sql):
        first = columns.split(',')[0].strip().split()[0]
        covered.add(f'{schema}.{table}.{first}')
    return covered
