import type { ExogenousFactorSeries } from '../../../src/database/seeds/schemas/exogenous-factors.schema';

type Measure = ExogenousFactorSeries['measureType'];
type Role = ExogenousFactorSeries['economicRole'];
export type WdiEntry = readonly [string, string, string, string, Measure, string, Role, string];

export const WDI_ENTRIES: readonly WdiEntry[] = [
  [
    'SH.H2O.BASW.ZS',
    'Acceso a servicios básicos de agua',
    'ST_081',
    'E',
    'PROPORTION',
    '% población',
    'OUTCOME',
    'Se reutiliza el indicador macro de agua básica; agua gestionada de forma segura no tiene observaciones para Bolivia en la consulta. No mide continuidad ni calidad municipal.',
  ],
  [
    'SH.STA.BASS.ZS',
    'Acceso a saneamiento básico',
    'ST_081',
    'E',
    'PROPORTION',
    '% población',
    'OUTCOME',
    'Se reutiliza el indicador macro de saneamiento básico; saneamiento gestionado de forma segura no tiene observaciones para Bolivia en la consulta. No equivale a alcantarillado municipal.',
  ],
  [
    'ER.H2O.FWST.ZS',
    'Estrés hídrico por extracción de agua',
    'PRD_CL09',
    'A,E',
    'PROPORTION',
    '% recursos disponibles',
    'CONDITION',
    'Indicador nacional de presión hídrica; no mide caudal de una cuenca.',
  ],
  [
    'ER.H2O.FWAG.ZS',
    'Participación agrícola en extracción de agua',
    'PRD_CL09',
    'A',
    'PROPORTION',
    '% extracción total',
    'EXPOSURE',
    'Exposición nacional de agricultura; no dato por finca.',
  ],
  [
    'AG.LND.IRIG.AG.ZS',
    'Tierra agrícola irrigada',
    'PRD_AG22',
    'A',
    'PROPORTION',
    '% tierra agrícola',
    'EXPOSURE',
    'Usar peso rezagado; cobertura nacional e historia irregular.',
  ],
  [
    'AG.LND.FRST.ZS',
    'Superficie forestal relativa',
    'PRD_CL11',
    'A',
    'PROPORTION',
    '% superficie terrestre',
    'EXPOSURE',
    'Proxy nacional de cobertura; no mide fragmentación ni biodiversidad.',
  ],
  [
    'AG.YLD.CREL.KG',
    'Rendimiento cerealero',
    'PRD_AG21',
    'A',
    'QUANTITY',
    'kg/ha',
    'OUTCOME',
    'Resultado agregado nacional; no rendimiento de cultivo o departamento individual.',
  ],
  [
    'EG.ELC.HYRO.ZS',
    'Participación hidroeléctrica',
    'PRD_EN13',
    'D',
    'PROPORTION',
    '% producción eléctrica',
    'OUTCOME',
    'Composición nacional anual; no equivale a despacho horario del SIN.',
  ],
  [
    'EG.ELC.NGAS.ZS',
    'Participación eléctrica de gas natural',
    'PRD_EN13',
    'D',
    'PROPORTION',
    '% producción eléctrica',
    'OUTCOME',
    'Composición nacional anual; no equivale a consumo volumétrico de gas.',
  ],
  [
    'EG.ELC.RNWX.ZS',
    'Electricidad renovable sin hidroelectricidad',
    'PRD_EN13',
    'D',
    'PROPORTION',
    '% producción eléctrica',
    'OUTCOME',
    'Composición nacional anual de renovables excluida hidroelectricidad.',
  ],
  [
    'SH.IMM.IDPT',
    'Inmunización DPT infantil',
    'ST_051',
    'Q',
    'PROPORTION',
    '% niños de 12-23 meses',
    'OUTCOME',
    'Cobertura estimada por vacuna; no notificaciones de enfermedad.',
  ],
  [
    'SH.IMM.MEAS',
    'Inmunización contra sarampión',
    'ST_051',
    'Q',
    'PROPORTION',
    '% niños de 12-23 meses',
    'OUTCOME',
    'Cobertura nacional estimada; no serie municipal.',
  ],
  [
    'SH.MED.BEDS.ZS',
    'Camas hospitalarias por población',
    'ST_047',
    'Q',
    'RATE',
    'camas/1000 personas',
    'EXPOSURE',
    'Capacidad nacional; no camas UCI ni disponibilidad diaria.',
  ],
  [
    'SH.MED.PHYS.ZS',
    'Médicos por población',
    'ST_047',
    'Q',
    'RATE',
    'médicos/1000 personas',
    'EXPOSURE',
    'Densidad nacional; no mide personal efectivo por turno.',
  ],
  [
    'SE.PRM.ENRL',
    'Alumnos matriculados en primaria',
    'ST_053',
    'P',
    'COUNT',
    'alumnos',
    'OUTCOME',
    'Matrícula agregada nacional; no población en edad escolar.',
  ],
  [
    'SE.SEC.ENRL',
    'Alumnos matriculados en secundaria',
    'ST_053',
    'P',
    'COUNT',
    'alumnos',
    'OUTCOME',
    'Matrícula agregada nacional; no asistencia cotidiana.',
  ],
  [
    'SE.PRM.CMPT.ZS',
    'Finalización de educación primaria',
    'ST_054',
    'P',
    'PROPORTION',
    '% grupo de edad pertinente',
    'OUTCOME',
    'Proxy de continuidad; no es tasa de abandono longitudinal.',
  ],
  [
    'SP.POP.0014.TO',
    'Población de 0 a 14 años',
    'ST_086',
    'P,Q,T',
    'COUNT',
    'personas',
    'EXPOSURE',
    'Estimación anual nacional; proxy del desglose territorial censal solicitado.',
  ],
  [
    'SP.POP.65UP.TO',
    'Población de 65 años o más',
    'ST_086',
    'Q,T',
    'COUNT',
    'personas',
    'EXPOSURE',
    'Estimación anual nacional; no recuento municipal censal.',
  ],
  [
    'SP.POP.DPND.YG',
    'Dependencia demográfica infantil',
    'ST_072',
    'P,T',
    'PROPORTION',
    '% población de 15-64 años',
    'EXPOSURE',
    'Menores de 15 respecto de población 15-64; no participación laboral.',
  ],
  [
    'SP.POP.DPND.OL',
    'Dependencia demográfica de mayores',
    'ST_072',
    'Q,T',
    'PROPORTION',
    '% población de 15-64 años',
    'EXPOSURE',
    'Mayores de 64 respecto de población 15-64; no carga efectiva de cuidados.',
  ],
  [
    'IT.NET.BBND.P2',
    'Banda ancha fija por habitantes',
    'ST_035',
    'J',
    'RATE',
    'suscripciones/100 personas',
    'OUTCOME',
    'Suscripciones fijas; no usuarios únicos ni cobertura territorial.',
  ],
  [
    'IT.NET.BBND',
    'Suscripciones de banda ancha fija',
    'ST_035',
    'J',
    'COUNT',
    'suscripciones',
    'OUTCOME',
    'Cantidad nacional; no conexiones móviles.',
  ],
  [
    'IT.CEL.SETS.P2',
    'Telefonía móvil por habitantes',
    'ST_038',
    'J',
    'RATE',
    'suscripciones/100 personas',
    'OUTCOME',
    'Proxy de acceso; puede superar 100 y no mide cobertura geográfica.',
  ],
  [
    'SL.AGR.EMPL.ZS',
    'Empleo agrícola sobre total',
    'MF_EMPLOYMENT_SECTOR',
    'A',
    'PROPORTION',
    '% empleo total',
    'OUTCOME',
    'Estimación modelada OIT; no registro empresarial.',
  ],
  [
    'BX.TRF.PWKR.CD.DT',
    'Remesas personales recibidas',
    'MF_REMITTANCES',
    'T,K',
    'FLOW',
    'USD corrientes',
    'OUTCOME',
    'Agregado anual nacional; no identifica origen ni plaza de pago.',
  ],
  [
    'BX.TRF.PWKR.DT.GD.ZS',
    'Remesas personales sobre PIB',
    'MF_REMITTANCES',
    'T,K',
    'PROPORTION',
    '% PIB',
    'EXPOSURE',
    'Dependencia anual; usar exposición previa al shock.',
  ],
  [
    'SP.URB.TOTL.IN.ZS',
    'Población urbana relativa',
    'ST_089',
    'L,E',
    'PROPORTION',
    '% población',
    'EXPOSURE',
    'Definición nacional de urbano; no densidad ni dato de barrio.',
  ],
];
